### ISSUE TITLE
TOC in Crowdin

### ISSUE THREAD

**Issue by FranzDeCopenhague** [nodejs/i18n#100]
If you look at crowding files to translated https://crowdin.com/project/nodejs/es-ES# and the _toc_md https://crowdin.com/translate/nodejs/163/en-es you can see that TOC points to modules doc and other docs. In case of modules documentation, we need to prevent the translation of the module name which uses to match the filename and the first heading inside the doc, and for the other docs should be nice to have the same translation in the TOC entry and the document title.

**Comment by FranzDeCopenhague** [comment]
Also the _toc.md contains a comment at the beginning, which is not required to translate and actually it is the first thing that an Spanish translator has done.
```
@// NB(chrisdickinson): if you move this file, be sure to update
@// tools/doc/html.js to point at the new location
```
I had a look at the other md files and I did not see any other comments. I suggest adding another comment on top of the comments to indicate not to translate the comments below at the beginning

**Comment by maddhruv** [comment]
@zeke @Andrulko can we do here like, just like glossaries, prevent the user from translating special comments

comments that start with special chars
`// ! this needs not to be translated`

**Comment by zeke** [comment]
> _toc.md contains a comment at the beginning

Yeah this is kind of annoying because it's the first thing you see, but it doesn't really matter if it gets translated or not. Once the file is parsed as HTML, the comment will be gone. So once it's translated in every language, translators won't have to pay attention to it any more.

> In case of modules documentation, we need to prevent the translation of the module name 

Yeah. We should land #91 once it's ready, then add all the module names to the glossary to help avoid confusion.

**Comment by Andrulko** [comment]
@maddhruv Are there many strings like ```// !``` in the source texts? Unfortunately, I didn't manage to find them here: https://crowdin.com/translate/nodejs/all/en-uk#q=%2F%2F+%21+

**Comment by alexandrtovmach** [comment]
Seems like it should be closed
