### ISSUE TITLE
I want to help to translate Node.JS documentation to Vietnamese, how can I start?

### ISSUE THREAD

**Issue by tiendq** [nodejs/i18n#102]
I came here from a tweet and this site https://crowdin.com/project/nodejs to look for detail but instead it made me more confused :)

Can I just start at crowdin.com?

What are I10n groups listed in readme file? I found [Vietnamese group](https://github.com/nodejs/nodejs-vi) is outdated and it even referred to `io.js`.

**Comment by zeke** [comment]
> it made me more confused :)

Sorry to hear that! What specifically made you confused? Let's try to improve it.

**Comment by tiendq** [comment]
@zeke As I said above, what's I18n groups for? and obsolete groups such as Vietnamese group is better removed. It had made me thought I need to be a member of this group to translate docs, but it turned out later I needn't :)

**Comment by zeke** [comment]
Good question! See https://github.com/nodejs/i18n/issues/19 for a discussion about that. If you have specific feedback or ideas on how to improve the experience of getting started, please open followup issues. 👍
