### ISSUE TITLE
Request: add Lithuanian language

### ISSUE THREAD

**Issue by interwebLT** [nodejs/i18n#150]
Hi,
Could you please add the Lithuanian language to crowdin.com node.js project?

**Comment by alexandrtovmach** [comment]
@interwebLT Hello, thanks for your interest in localization process of Node.js.
Do you still interested in that we can add Lithuanian language to the list?

**Comment by interwebLT** [comment]
@alexandrtovmach 
Hello, thanks for contacting.. 
Yes, I do! It would be pleasure to help.

**Comment by alexandrtovmach** [comment]
Added Lithuanian language here:
https://crowdin.com/project/nodejs/lt

welcome on board =)
