### ISSUE TITLE
The names of the teams/wg should be translated? 

### ISSUE THREAD

**Issue by mcollina** [nodejs/i18n#157]
In my opinion no. I think those have to be treated as proper names.

**Comment by zeke** [comment]
Hi @mcollina 👋. Can you elaborate on what you're asking here? I think I'm missing some context.

**Comment by mcollina** [comment]
In https://github.com/nodejs/nodejs.org/pull/1762, Community Committee and Technical Steering Committee are getting translated. I do not think they should, as they are proper names.

**Comment by zeke** [comment]
`Community Committee` and `Technical Steering Committee` could be good candidate terms to add to the Crowdin glossary, so translators will see a message about what the string means and why it should not be translated. @maddhruv has a WIP pull request for glossary terms here: https://github.com/nodejs/i18n/pull/91

**Comment by nschonni** [comment]
@zeke These are in the glossary now https://github.com/nodejs/i18n/blob/master/crowdin-glossary.json#L16-L35
Think this can be closed
