### ISSUE TITLE
automatic approve and merge translation PRs

### ISSUE THREAD

**Issue by maddhruv** [nodejs/i18n#161]
There's no code in the PRs to be reviewed and merged manually everytime
can we do something to timely accept and merge the PRs

**Comment by zeke** [comment]
@dependabot might be good for this.

https://twitter.com/zeke/status/1043219917913219072

**Comment by maddhruv** [comment]
so https://probot.github.io/ is something that might help us go ahead

**Comment by zeke** [comment]
Probot is a framework for building bots. We could build a custom bot to merge Crowdin PRs, but I think if there's something that already exists to solve this problem, we should consider using it.

**Comment by maddhruv** [comment]
Yeah indeed!
But would the _2 approvals merge block_ setting hurdle the bot?

**Comment by zeke** [comment]
We can change that setting if needed. I initially enabled the approvals requirement to ensure that people who want to participate in this effort don't miss out.

**Comment by RichardLitt** [comment]
I moved it to 1, with @zeke's approval on the call today. Closing.
