### ISSUE TITLE
i18n breakout session at the Node.js Collaborator's Summit–October 13th

### ISSUE THREAD

**Issue by obensource** [nodejs/i18n#164]
# Description
We're on for an i18n breakout session at the Node.js Collaboration Summit in Vancouver BC, on October 13th. This directly follows the [Node + JS Interactive](https://events.linuxfoundation.org/events/node-js-interactive-2018/) conference.

I'll be leading the session, and would really love input for anything y'all would like to share or that you think should be covered. If you're planning on being in attendance, please let me know and we can co-lead!

What should we cover?

**Comment by obensource** [comment]
@littledan @srl295 : if y'all are planning on attending the collaborator's summit, I'd also love to open up some of this time to discuss the relationship between the Node.js i18n WG and ECMA 402–how we can mutually support each other and continue to expand our collaboration. 🚀

**Comment by zeke** [comment]
👋 greetings from afar. Not gonna make it, but have a great session!

**Comment by littledan** [comment]
Unfortunately I won't be there either. I'd be happy to call in, though!

**Comment by srl295** [comment]
Nor will I be there, regrettably.

>

**Comment by RichardLitt** [comment]
I also will not be able to attend this one, and will be on a ✈️ when it is happening.

**Comment by obensource** [comment]
This is a super big bummer, but it's likely that I might not make it to NJSI/NodeSummit either. My partner may have to have an emergency surgery this week and I'll need to be there for her and our family if so. 😞

I'll be in touch if I'm able to make it and y'all are still interested in calling in. :)

**Comment by zeke** [comment]
Sorry to hear that, @obensource. Wishing you and your family well.

**Comment by RichardLitt** [comment]
It happens, @obensource! Wishing you well too. :)

**Comment by obensource** [comment]
Thank you all. Looking forward to being in touch regardless. ❤️
