### ISSUE TITLE
add Persian to the being translated list

### ISSUE THREAD

**Issue by AliSawari** [nodejs/i18n#180]
@nodejs/nodejs-fa is actively translating [Nodejs Website](https://nodejs.org)
@nodejs-crowdin please add the language in [Nodejs Translations in Crowdin](https://crowdin.com/project/nodejs)
thank you

[Related discussion](https://crowdin.com/project/nodejs/discussions/2/0/home)

**Comment by alexandrtovmach** [comment]
@AliSawari Hello, thanks for your interest in localization process of Node.js.
Do you still interested in that we can add Persian language to the list?

**Comment by alexandrtovmach** [comment]
Closing as unactive 😞 
Feel free to open new language request issue
