### ISSUE TITLE
isolate the module and docs

### ISSUE THREAD

**Issue by maddhruv** [nodejs/i18n#186]
The concern I want to raise here is about isolating the module/script that we use for collecting the node versions docs and the translated _docs_ into two different branches
- _master_ branch - docs (en + translated)
- _module_ branch - module (i18n) and scripts

#### Why?
It is very difficult to clone/pull all these translated file/docs every time, which is an unnecessary flow if one wants to write some scripts/module

**Comment by maddhruv** [comment]
but even if we are to publish the module, will we be publishing all the content as well?

**Comment by amorist** [comment]
just json file

**Comment by amorist** [comment]
or load content from master branch (master branch - docs (en + translated))

**Comment by maddhruv** [comment]
the problem that shall persist is about cloning the whole repo with translated content every time?

**Comment by amorist** [comment]
#133

**Comment by zeke** [comment]
> It is very difficult to clone/pull all these translated file/docs every time

@maddhruv can you describe in more detail what is difficult about this process?

**Comment by maddhruv** [comment]
Whenever I clone or fetch the repo
There are thousands of files - translated docs
Which need to be fetched

**Comment by maddhruv** [comment]
can't we do both the things separate as
- translated docs is a separate module
- translate script/module is separate
?

**Comment by alexandrtovmach** [comment]
It's not an issue anymore, because we're using Crowdin
