### ISSUE TITLE
Request : Add Telugu Language

### ISSUE THREAD

**Issue by svenkatreddy** [nodejs/i18n#187]
Hi,

I would like to join & contribute translations for Telugu.
Wiki: https://en.wikipedia.org/wiki/Telugu_language
Total Telugu speaking population: 81 million
Just for stats: It is the most widely spoken member of the Dravidian language family which puts ahead of other languages which are supported.

Lot of software engineers in U.K/U.S. are from telugu speaking background.
Reference: https://www.bbc.com/news/world-45902204
Telugu speaking population by geographical area: https://en.wikipedia.org/wiki/Telugu_diaspora

I think it's a good start to supporting it.

**Comment by maddhruv** [comment]
Ref - https://github.com/nodejs/i18n/issues/169

**Comment by maddhruv** [comment]
I am closing this issue
feel free to reopen if necessary

**Comment by svenkatreddy** [comment]
"The languages we have selected are based on the statistics of the geographic audience the nodejs website has, and I don't think telugu could have much audience with respect to the efforts we put into translating into it"
How does nodejs sum geographic audience ?
if it is by region, there are good amount of people who speak telugu doesn't stay in region ex: United States.
Good example we have is Tamil, benagli which nodejs already supports it ?

**Comment by zeke** [comment]
Thanks for opening this issue, @svenkatreddy. Here's some historical context on why we chose the initial set of languages: https://github.com/nodejs/i18n/issues/70

In general, the Electron i18n project (the localization model on which the Node.js i18n project is largely based) has enabled all languages as translators have requested them, with the exception of Venezuelan Spanish, which our Spanish-speaking translators recommended against, as the language is not significantly different from the existing country-agnostic "Spanish" that we already support. See https://github.com/electron/i18n/issues/281

Considering that we've now had two folks express interest in helping translate Node.js docs to Telugu, I'd be in favor of enabling it.

**Comment by veera83372** [comment]
@svenkatreddy Count me in as well, I would like to be part of it

**Comment by alexandrtovmach** [comment]
@svenkatreddy @veera83372  Hello, thanks for your interest in localization process of Node.js.
Do you still interested in that we can add Telugu language to the list?

**Comment by svenkatreddy** [comment]
@alexandrtovmach Yes, thanks.

**Comment by alexandrtovmach** [comment]
@svenkatreddy Added here: https://crowdin.com/project/nodejs/te

Please read https://github.com/nodejs/i18n/blob/master/GETTING_STARTED.md
