### ISSUE TITLE
Audit of our l10n groups

### ISSUE THREAD

**Issue by obensource** [nodejs/i18n#19]
## Purpose
A continuation of [this Node.js Community Committee issue](https://github.com/nodejs/community-committee/issues/239).

## Description
Since we're picking up steam with implementing a new i18n process, an audit of all of the existing Node.js l10n groups is in order to determine a few things:

* Is the group active, and/or would they like to continue the l10n group?
* Who're the currently active members, and/or who has expressed interest in pushing the group forward?

**After the gathering of this information, we can then create issues regarding the following, and accomplish these (in sequential order):**
1. Request that currently active group members (or people who'd like to resurrect a group, or start a new one) update their l10n group's membership lists, and add themselves to bring the group info up to date.
2. Agree upon a general procedure for l10n membership
3. PR a new membership procedure doc for every l10n repo
4. PR a how-to-contribute doc for every l10n repo–essentially outlining how to create a Crowdin Node.js l10n project and how to use Crowdin.
5. Archive inactive l10n groups and reduce the repo noise in Node.js

**Comment by lukaszewczak** [comment]
Hi @obensource Is this audit already being created somewhere?  I can try to prepare this kind of audit in the next week , but where to put it, here or somewhere else (maybe some google sheets)?

Regarding polish l10n repo nodejs-pl I now that I would like to resurrect a group or start a new one.

**Comment by lukaszewczak** [comment]
Hi, I'm wonder is there a possibility to group all l10n group's inside organisation . Is this only available through new organisations? I think that this would be simpler to manage those groups if we would have one place to go to see all l10n group's. What do you think about it?

**Comment by obensource** [comment]
@lukaszewczak that's awesome that you'd like to get the [polish l10n group](https://github.com/nodejs/nodejs-pl) going! I recommend reaching out to @m1halo and seeing if he's still interested in helping out with that as well. You could then start collaborating on that existing repo and make it awesome! Exciting! 🙌

#### Re Audits:
The exact form our audit will take will be more defined after we discuss it at our next WG meeting on the 6th. Definitely feel free to jump in and help with that task after we define it, thanks for offering!

Currently I'm imagining it won't be much more than writing some nice copy for an issue that we file in every l10n repo (eg. as [we did with the recent proposal](https://github.com/nodejs/nodejs-pl/issues/6)). With the response we receive we'll be able to determine the answer to the bullet point questions listed in this issue, and then move along from there. I'd like to at least discuss it at the WG meeting before we do that though, to see if anyone has insight or context about more relevant ways to connect with some of the groups.

#### Re Grouping l10n groups:
I think after the audit, we should add a list of all the current l10n groups that we maintain a relationship with to our [README](https://github.com/nodejs/i18n/blob/master/README.md) for easy reference. That's definitely something we're missing!

Beyond that it's fairly explicit in our [Summary of Responsibilities](https://github.com/nodejs/i18n/blob/master/README.md#summary-of-our-responsibilities) that we want each l10n group to be autonomous and maintain their own interests (and repos), and simply refer to us as an entry point for getting their work into Node.js. I don't think our i18n WG should be thought of as a manager of l10n groups or overarching authority necessarily, but more so an enabler of them all. 🎉

Please let me know if I answered your questions, or if I missed anything. Thanks a bunch!

**Comment by obensource** [comment]
@lukaszewczak sorry, I pinged the wrong person. I meant to refer you to @mthenw! :D

**Comment by lukaszewczak** [comment]
@obensource , thank you for the responses and explanations. Thanks for contact to polish group maintainer.

I cannot be on WG meeting on the 6th, but after you define this audit task, I would like to help with that.

About putting list of all the current l10n groups I prepare PR #28

**Comment by RichardLitt** [comment]
For this audit: We should contact each of the localization groups and request that they be in charge of their CrowdIn translations for their languages. I think that asking this at the same time as the audit will be smart, as it will help us see whether they are active enough to take on an actionable item, as opposed to just having some people respond "Yeah, we're around". A bit sneaky, but I think effective.

My suggestion is that we use [name-your-contributors](https://github.com/mntnr/name-your-contributors) to audit each's group activity by member, and then add that information into the issue that we open to check on their activity and responsiveness. I can help set up a template for this, I think, if other's agree on that method.

**Comment by lukaszewczak** [comment]
Hi @RichardLitt, I am not convinced that your effort to prepare this tool (name-your-contributors ) is necessary. It looks like almost all l10n groups are inactive from about 2/3 years, even when @obensource send on every group issue `Node.js Internationalization Proposal` (almost 1 month ago), there was almost no response, not even emoticon, thumb up - some reactions like emoticon/comments was only on this repos, which shows who is potentially interested/active member:
- https://github.com/nodejs/nodejs-es/issues/149
- https://github.com/nodejs/nodejs-nl/issues/17, 
- https://github.com/nodejs/nodejs-id/issues/55
- https://github.com/nodejs/nodejs-pt/issues/68
- https://github.com/nodejs/nodejs-tr/issues/132
-  https://github.com/nodejs/nodejs-de/issues/29
- https://github.com/nodejs/nodejs-ja/issues/122
- https://github.com/nodejs/nodejs-uk/issues/93
- https://github.com/nodejs/nodejs-zh-TW/issues/142
- https://github.com/nodejs/nodejs-fr/issues/89
- https://github.com/nodejs/nodejs-nl/issues/17
- https://github.com/nodejs/nodejs-he/issues/17
- https://github.com/nodejs/nodejs-it/issues/18
- https://github.com/nodejs/nodejs-hi/issues/17
- https://github.com/nodejs/nodejs-pl/issues/6

I think that we can assume that who is interested in moving group forward reacted to those issues.

For example, to contact owner of the polish group I need to contact him threw a Twitter and he then set up me as an admin for this polish groups, so this shows up that if someone is not interested in the group, he will not event try to respond thru github.

It looks like @obensource issue make a good audit for those groups, and show potential interested memebers/groups and maybe we just should stick to this groups I mention and others should be archived?

**Comment by laosb** [comment]
I'm in nodejs-cn and I could see some reactions actually. How about adding nodejs-cn to that list?

**Comment by obensource** [comment]
@RichardLitt @lukaszewczak @laosb I think skimming each group with `name your contributors` is a good idea to get solid activity viz that adds to the response we've already seen to the proposal. Combining what we have already and what we get from that will help us document current l10n activity for ourselves and others here as we move along.

I agree that the proposal reach out was telling as to who is active in those repos, however I think it's will be cordial and good to make contact again–requesting help, and providing a roadmap for how l10n groups can contribute via Crowdin & us. We should only need to reach out to the groups who we've identified as active either by response to the proposal, or recent activity via `name-your-contributors`. 😎

Thanks all! 🙌

**Comment by RichardLitt** [comment]
I've gone through and basically audited. I didn't get usernames, but I got what name-your-contributors could get. I ignored reactions, but I could try and get those, too. 

[Sourcecode](https://github.com/RichardLitt/node-i18n-audit)

This doesn't get commits at the moment, and most of the issue comments where there is no new issue were probably in response to @obensource's issue (which I filtered out, along with `@hackygolucky` as I saw her a few times and assumed she was posting on node business.)

Thoughts?

# Node i18n Groups Audit

## nodejs/nodejs-es audit

_This list was automatically generated with the following command:_

```sh
$ name-your-contributors -u nodejs -r nodejs-es -a 2017-03-01
```

There were 4 issue commentators who made 5 comments.
There were 1 reviewers who made 1 review comments.
There were 2 issue creators who made 2 issues.
There were 0 PR commentators who made null comments.
There were 1 PR creators who made 2 prs.

## nodejs/nodejs-nl audit

_This list was automatically generated with the following command:_

```sh
$ name-your-contributors -u nodejs -r nodejs-nl -a 2017-03-01
```

There were 1 issue commentators who made 1 comments.
There were 0 reviewers who made null review comments.
There were 0 issue creators who made null issues.
There were 0 PR commentators who made null comments.
There were 0 PR creators who made null prs.

## nodejs/nodejs-id audit

_This list was automatically generated with the following command:_

```sh
$ name-your-contributors -u nodejs -r nodejs-id -a 2017-03-01
```

There were 1 issue commentators who made 1 comments.
There were 0 reviewers who made null review comments.
There were 1 issue creators who made 1 issues.
There were 0 PR commentators who made null comments.
There were 0 PR creators who made null prs.

## nodejs/nodejs-pt audit

_This list was automatically generated with the following command:_

```sh
$ name-your-contributors -u nodejs -r nodejs-pt -a 2017-03-01
```

There were 9 issue commentators who made 11 comments.
There were 1 reviewers who made 1 review comments.
There were 0 issue creators who made null issues.
There were 0 PR commentators who made null comments.
There were 1 PR creators who made 1 prs.

## nodejs/nodejs-tr audit

_This list was automatically generated with the following command:_

```sh
$ name-your-contributors -u nodejs -r nodejs-tr -a 2017-03-01
```

There were 6 issue commentators who made 7 comments.
There were 1 reviewers who made 1 review comments.
There were 1 issue creators who made 1 issues.
There were 0 PR commentators who made null comments.
There were 1 PR creators who made 1 prs.

## nodejs/nodejs-de audit

_This list was automatically generated with the following command:_

```sh
$ name-your-contributors -u nodejs -r nodejs-de -a 2017-03-01
```

There were 3 issue commentators who made 6 comments.
There were 0 reviewers who made null review comments.
There were 0 issue creators who made null issues.
There were 2 PR commentators who made 2 comments.
There were 1 PR creators who made 1 prs.

## nodejs/nodejs-ja audit

_This list was automatically generated with the following command:_

```sh
$ name-your-contributors -u nodejs -r nodejs-ja -a 2017-03-01
```

There were 5 issue commentators who made 18 comments.
There were 0 reviewers who made null review comments.
There were 1 issue creators who made 1 issues.
There were 2 PR commentators who made 4 comments.
There were 1 PR creators who made 2 prs.

## nodejs/nodejs-uk audit

_This list was automatically generated with the following command:_

```sh
$ name-your-contributors -u nodejs -r nodejs-uk -a 2017-03-01
```

There were 6 issue commentators who made 7 comments.
There were 0 reviewers who made null review comments.
There were 1 issue creators who made 1 issues.
There were 0 PR commentators who made null comments.
There were 0 PR creators who made null prs.

## nodejs/nodejs-zh-TW audit

_This list was automatically generated with the following command:_

```sh
$ name-your-contributors -u nodejs -r nodejs-zh-TW -a 2017-03-01
```

There were 1 issue commentators who made 1 comments.
There were 0 reviewers who made null review comments.
There were 0 issue creators who made null issues.
There were 0 PR commentators who made null comments.
There were 0 PR creators who made null prs.

## nodejs/nodejs-fr audit

_This list was automatically generated with the following command:_

```sh
$ name-your-contributors -u nodejs -r nodejs-fr -a 2017-03-01
```

There were 4 issue commentators who made 6 comments.
There were 0 reviewers who made null review comments.
There were 1 issue creators who made 1 issues.
There were 0 PR commentators who made null comments.
There were 0 PR creators who made null prs.

## nodejs/nodejs-nl audit

_This list was automatically generated with the following command:_

```sh
$ name-your-contributors -u nodejs -r nodejs-nl -a 2017-03-01
```

There were 1 issue commentators who made 1 comments.
There were 0 reviewers who made null review comments.
There were 0 issue creators who made null issues.
There were 0 PR commentators who made null comments.
There were 0 PR creators who made null prs.

## nodejs/nodejs-he audit

_This list was automatically generated with the following command:_

```sh
$ name-your-contributors -u nodejs -r nodejs-he -a 2017-03-01
```

There were 2 issue commentators who made 4 comments.
There were 0 reviewers who made null review comments.
There were 0 issue creators who made null issues.
There were 0 PR commentators who made null comments.
There were 0 PR creators who made null prs.

## nodejs/nodejs-it audit

_This list was automatically generated with the following command:_

```sh
$ name-your-contributors -u nodejs -r nodejs-it -a 2017-03-01
```

There were 4 issue commentators who made 5 comments.
There were 0 reviewers who made null review comments.
There were 0 issue creators who made null issues.
There were 0 PR commentators who made null comments.
There were 0 PR creators who made null prs.

## nodejs/nodejs-hi audit

_This list was automatically generated with the following command:_

```sh
$ name-your-contributors -u nodejs -r nodejs-hi -a 2017-03-01
```

There were 13 issue commentators who made 19 comments.
There were 0 reviewers who made null review comments.
There were 1 issue creators who made 1 issues.
There were 0 PR commentators who made null comments.
There were 0 PR creators who made null prs.

## nodejs/nodejs-pl audit

_This list was automatically generated with the following command:_

```sh
$ name-your-contributors -u nodejs -r nodejs-pl -a 2017-03-01
```

There were 1 issue commentators who made 1 comments.
There were 0 reviewers who made null review comments.
There were 0 issue creators who made null issues.
There were 0 PR commentators who made null comments.
There were 0 PR creators who made null prs.

**Comment by obensource** [comment]
@RichardLitt amazing! Thanks so much for making this happen! I think between this and @lukaszewczak's research–we can safely contact the right people and reform our l10n groups around whoever is interested making them happen. I can help begin connecting the channels between the l10n groups and the i18n WG this week. 👍

**Comment by RichardLitt** [comment]
Cool. Let me know if you want the people's names, too - trivial to get. I discarded them somewhat hastily from this initial grep.

**Comment by obensource** [comment]
@RichardLitt I think it would be beneficial to grab people's names as well–awesome thanks. 🍻

Once we have those we should have all we need to start reaching out to all active, or potentially active members of each group and request that they update their members list and begin to connect with other translators to get involved with their respective group! 🙌

Wahoo! Time to really begin building ongoing relationships with l10n groups! 🎉

**Comment by Tiriel** [comment]
Oooooooookay!  Sorry folks, I'm back!

I think you also need the name of the people who opened PRs on the global nodejs.org repo. I know (having been one of them) that many people didn't contribute to their l10n groups because the groups were dead and they didn't have commit rights, but instead directly committed i18n files on the main website repo.

A concrete example, I was added recently (like two months ago) to the nodejs-fr team, I think I'm the only people having opened an issue there mentioned in @RichardLitt 's stats , but I submitted several pages of translations directly in the nodejs.org repo because I wasn't part of the localized team and had no commit right.

I confess I don't know how, but I think this should be taken into account.

**Comment by zeke** [comment]
Judging by the [reactions to @obensource's messages](https://github.com/nodejs/i18n/issues/19#issuecomment-371017038) in each of the localization repos, people are excited and ready to embrace the new model.

I propose that we update the descriptions and READMEs of each of those old repositories with a message about the new setup and a link to this nodejs/i18n repository, then archive all the repos. This way they can still be accessed but will be in a read-only state. What do @nodejs/i18n folks think? 👍 / 👎

**Comment by Tiriel** [comment]
I'm definitely a +1 to @zeke 's idea. I was wondering myself lately what was the point of keeping these repos open tbh. Will we have use for the in the future?

**Comment by obensource** [comment]
@zeke 💯

@Tiriel I think the benefit of keeping the l10n repos around may be that it provides a landing point for anyone looking to contribute to a specific language, and if needed–can be a point of communication between the i18n group and l10n champions (reviewers) who're responsible for ensuring translation quality. This is how I imagined it–but it may in fact be unnecessary and we should definitely revisit this conversation again after we observe activity over time to determine their usefulness. 👍

**Comment by JCMais** [comment]
Sounds great, should we start updating the projects README to point to this repo?

**Comment by zeke** [comment]
I think that's a good idea, @JCMais 👍

**Comment by fhemberger** [comment]
Somewhat related: We should also check if we still need the `nodejs/nodejs-*` repositories. They date back from io.js (2015) and were meant for translators to coordinate, but many of them have not been touched ever since.

Most translation related discussions happen directly in the PRs on `nodejs/nodejs.org`.

**Comment by obensource** [comment]
The i18n WG considers this work to be complete, closing.
