### ISSUE TITLE
Request | Add Serbian Language

### ISSUE THREAD

**Issue by BrsJsk** [nodejs/i18n#191]
Hi,

I would like to join and contribute translations for Serbian.
I don't know if you need Serbian translations as it's not enabled in crowdin.com.
If it gets enabled, I would be happy to join and contribute.

**Comment by ljuba95** [comment]
+1 would also help with this.

**Comment by maleta** [comment]
+1

**Comment by alexandrtovmach** [comment]
@BrsJsk @ljuba95   Hello, thanks for your interest in localization process of Node.js.
Do you still interested in that we can add Serbian language to the list?

**Comment by maleta** [comment]
+1 interested and available to assist

**Comment by alexandrtovmach** [comment]
@maleta Sounds great, could you advise which of these options is better?
![image](https://user-images.githubusercontent.com/28801003/77709665-83034180-6fd4-11ea-8a73-a7dfd23d1de1.png)

**Comment by maleta** [comment]
Both languages are official. If we have to choose one, my vote goes for Latin version.

**Comment by alexandrtovmach** [comment]
Okay, seems like it's really debatable:
https://ciklopea.com/localization/digital-marketing-localization/should-you-localize-to-serbian-latin-or-to-serbian-cyrillic/

Added Serbian Latin: https://crowdin.com/project/nodejs/sr-CS
Before start translating please read: https://github.com/nodejs/i18n/blob/master/GETTING_STARTED.md

**Comment by maleta** [comment]
Indeed it is. Font base for Latin version is much larger, that's why I voted for it. 
Thanks!

**Comment by BrsJsk** [comment]
Agreed. Latin version is better to use.

**Comment by BrsJsk** [comment]
Will there be a maintainer, someone who approves the translations?

**Comment by alexandrtovmach** [comment]
@BrsJsk https://github.com/nodejs/i18n/blob/master/GETTING_STARTED.md#proofreading
