### ISSUE TITLE
Request to join the group

### ISSUE THREAD

**Issue by celyes** [nodejs/i18n#192]
Hi everyone.
i would like to ask you about the method in which i'll be a member in the internationalization group.
@Aissaoui-Ahmed and I have been working on the Arabic translation of the website and we would like to be deeply involved by joining the internationalization group for the node.js
Thank you all.

**Comment by Aissaoui-Ahmed** [comment]
Hello 
Me and @celyes are excited to join
@obensource and @zeke any permission to open pull request !

**Comment by zeke** [comment]
Yes please go ahead and open a pull request 👍

**Comment by amorist** [comment]
Done.
