### ISSUE TITLE
Request to join the group

### ISSUE THREAD

**Issue by Alex-Temny** [nodejs/i18n#193]
Good day.
I'd like to join i18n Working Group.
I've been contributing mostly for some non-open source projects about web-technologies since the end of 2017 as a translator (English->Russian/Ukrainian).
And I'd like to begin making something useful for open source projects (especially for Node.js) as well.

**Comment by zeke** [comment]
Hey @Alex-Temny! Thanks for your interest. You can I chatted over email earlier, and you shared some of your existing work, like https://tutsplus.com/authors/alexey-temnykov -- great stuff!

We'd love to have you in the working group. Please open a pull request on this repo, adding yourself to the member list here: https://github.com/nodejs/i18n#current-members

**Comment by Alex-Temny** [comment]
Hi, @zeke. I've just opened the pull request (first ever on GitHub).
I hope that everything is OK with it.

**Comment by amorist** [comment]
Done #194
