### ISSUE TITLE
Request to become a proofreader on CrowdIn

### ISSUE THREAD

**Issue by Alex-Temny** [nodejs/i18n#198]
Hi.
I joined the Node.js i18n Working Group near a month ago.
I've translated just 1 file on CrwodIn since that time. --> https://crowdin.com/translate/nodejs/48/en-ru
While translating I found some little issues in the original documentation. I've made the PR to fix them --> https://github.com/nodejs/node/pull/27853
That PR was approved.
So, I understand what I'm translating.
I'd like to ask to make me a proofreader for Russian (my native language).
(probably I could even be a good proofreader for the original documentation)
Also Node.js is my favourite technology I'd like to use myself in the future for my own little projects (I'm not a professional programmer though).
And by translating/proofreading the Node.js docs I can better understand it.

Also I have some questions.
So, the docs on nodejs/node repository were updated when the PR mentioned above was approved.
But, as far as I understand, the docs on CrowdIn were not updated automatically (they still contain the issues corrected on nodejs/node).
I think a lot of users (including me) will find even more issues with docs in the future.
So, how does the updating of the docs happen on Crowdin (manually by managers, right)?

While chatting with @zeke  a month ago over email before joining the group he mentioned that 
it's possible to consider getting me Manager permissions on the Crowdin project so that I could more effectively contribute.
So, I'd like to ask to consider the possibility to give me the Manager permissions there.
That would be great experience for me. And I'd like to see how the CrowdIn translation process looks like from the perspective of the managers.
If that's not possible, it's ok. I'd be glad with proofreader position.

Also I've been translating for TutsPlus translation project for over 1 year (https://tutsplus.com/authors/alexey-temnykov) and I have quite big term bases and translation memories I could probably share/upload to CrowdIn which could help to facilitate the translation process for translators into Russian.

**Comment by zeke** [comment]
Hey @Alex-Temny.

> the docs on nodejs/node repository were updated when the PR mentioned above was approved.
But, as far as I understand, the docs on CrowdIn were not updated automatically

Correct. The translations in this nodejs/i18n repo come from Crowdin, and are not at all related to the translations that live in nodejs/node.

> While chatting with @zeke a month ago over email before joining the group he mentioned that
it's possible to consider getting me Manager permissions on the Crowdin project

I think I mentioned **Proofreader** permissions, which gives you the ability to override existing translations in the languages where you have Proofreader status. This is different from the **Manager** role, which has more administrative permissions to the entire project. For details on these roles, see https://support.crowdin.com/online-editor/#proofreadingvoting-mode

I'm +1 on assigning you Proofreader status in Crowdin. 👍

**Comment by Alex-Temny** [comment]
ok, sorry for misunderstanding. Proofreader permissions would be great for me.
thanks

**Comment by Alex-Temny** [comment]
as for
"I think I mentioned Proofreader permissions...",

I intentionally checked my Gmail email and I can clearly see
"...once you're in the group, we can consider getting you Manager permissions 
on the Crowdin project so you can more effectively contribute..."

--> "..Manager permissions..."

**I'll be more than happy with proofreader status.**

But it's **just strange** to see here "I think I mentioned Proofreader permissions" and 
"...consider getting you Manager permissions.." in the message sent from your email.

That's where this **confusion** comes from.
Cause I was trying to follow instructions provided in the message sent from your account.
Maybe you could check the message sent from your email to me (April 21, 2019) and confirm that you see "..Proofreader permissions.".
Cause in that case this might mean that either Gmail began to change information
it transfers between the users, or someone else sends messages from your email,
and you should be aware of this.

**Comment by zeke** [comment]
Sorry about that. I misspoke. The *Proofreader* role should give you enough access to do what you're hoping to do.

**Comment by zeke** [comment]
I've made you a proofreader for Russian in Crowdin. Please take a look and let me know if it's working for you.

<img width="1003" alt="Screen Shot 2019-06-19 at 4 37 17 PM" src="https://user-images.githubusercontent.com/2289/59808311-98fb0d80-92b0-11e9-9f14-f6283df22c12.png">

Details at https://support.crowdin.com/online-editor/#proofreadingvoting-mode

**Comment by alexandrtovmach** [comment]
@Alex-Temny If everything works okay, this issue should be closed
