### ISSUE TITLE
Translators for our WG Meetings

### ISSUE THREAD

**Issue by obensource** [nodejs/i18n#20]
## Purpose
We'd like everyone involved in our WG to have the same understanding of what's going on, and be able to have the same opportunity to weigh in on every decision we make–without being held back by a language barrier.

## Description
As @RichardLitt brought up in the discussion around our [first i18n WG meeting](https://github.com/orgs/nodejs/teams/i18n/discussions/1): It would be advantageous to start searching for "on call" translators for our WG calls. This is probably an achievable goal if we reach out to the community via CommComm, Twitter, and our l10n groups.

## TODO
* Bring this up in the next [CommComm meeting](https://github.com/nodejs/community-committee/issues/245) and seek help
* Reach out to the Node.js community via Twitter
* Create an issue in the l10n groups who represent the same language preferences as the members of our i18n WG.

**Comment by RichardLitt** [comment]
Thanks, @obensource! For this next call, I think we should wait until it is scheduled, and then field requests for translators from participants. Do you know when the next CommComm meeting is?

**Comment by obensource** [comment]
@RichardLitt the [next CommComm meeting](https://github.com/nodejs/community-committee/issues/245) is tomorrow. I provided the wrong link above, apologies–updated it. :)

I'll secure the date of our next meeting on Friday, and then we can see if participants need translation help, definitely. Thank you Richard! 👍

**Comment by obensource** [comment]
### Post CommComm-meeting update
@zibbykeaton gave us the go ahead to ping her when we need help to field & request assistance from translators in our community via the Node.js twitter profile. Thanks Zibby! 🎉🎉🎉

**Comment by FranzDeCopenhague** [comment]
I just sign-in the Monday doodle

**Comment by ZibbyKeaton** [comment]
Yes, please just ping me with your needs and I can share info on social and also send notes to Node.js Foundation members to see if they can support here too.

**Comment by ZibbyKeaton** [comment]
Checking in to see if there's anything needed this week or next in promoting efforts here? If so, just send me an email zkeaton@linuxfoundation.org or comment here, so I can stay up to speed with support.

**Comment by obensource** [comment]
Thank you @ZibbyKeaton! 🍻

At present, I believe the goal is to reach out as necessary if anyone expresses a need for translation. That need wasn't expressed for our first meeting yesterday, but I'm sure it will be in future meetings–so we will reach out as it arises. Thanks so much for helping us out in this way and being super awesome! 😎

**Comment by AugustinMauroy** [comment]
Can you give news for this discussion. It's out of date?
