### ISSUE TITLE
Request to join the group

### ISSUE THREAD

**Issue by alexandrtovmach** [nodejs/i18n#202]
Hello,
I'd like to join i18n Working Group.

I'm already working on a translating original website [nodejs.org](nodejs.org) and API docs. Want to simplify the process to involve more translators in it and prepare content to migration to the new website.

PR with adding to a memberlist: #201 
Related issue: #72

**Comment by zeke** [comment]
PR https://github.com/nodejs/i18n/pull/201 has landed. Welcome to the group! 🙌
