### ISSUE TITLE
Request to join the group

### ISSUE THREAD

**Issue by JohnTitor** [nodejs/i18n#203]
Hi, I'd like to join the i18n group.

I've worked in some open-source communities for [translations](https://crowdin.com/profile/huyuumi). I'd like to work in Node.js also.

/cc @zeke

**Comment by zeke** [comment]
Hi @JohnTitor. Thanks for your interest. Would your goal be to translate content? If so, you can head over to https://crowdin.com/project/nodejs, log in with your GitHub account, and start translating right away!

If you wish to also join the group, you're welcome to, but it's not strictly necessary if your aim is to translate.

**Comment by JohnTitor** [comment]
@zeke Thanks for replying! Yes, I'd like to translate but I'd also like to join the group and do more things. Could I open a pull request to add me?

**Comment by zeke** [comment]
Could I open a pull request to add me?

👍

**Comment by JohnTitor** [comment]
I opened #204.

**Comment by JohnTitor** [comment]
Also, I've translated 1000+ words, could I become a proofreader? (I'm not sure the best place to link on Crowdin...)

![image](https://user-images.githubusercontent.com/25030997/61582366-fced4c00-ab64-11e9-9d36-52b589600455.png)

**Comment by zeke** [comment]
@JohnTitor I've promoted you to Japanese Proofreader on Crowdin, and approved your request to join the working group!

**Comment by JohnTitor** [comment]
Thanks! Closes via #204

**Comment by JohnTitor** [comment]
One minor question: could I also join the i18n team in Node.js org?

**Comment by JohnTitor** [comment]
@zeke ^

**Comment by zeke** [comment]
Hey @nodejs/i18n, what's the protocol for adding someone to the @nodejs org? 

![Screen Shot 2019-07-20 at 2 29 20 PM](https://user-images.githubusercontent.com/2289/61584327-ca0e6e00-aafa-11e9-9932-bd37f1ea4fba.png)

**Comment by JohnTitor** [comment]
@zeke Hmm, is something wrong? Could you click me and "Invite" button? Usually, maintainers can invite someone to the team. Or you may be able to invite to nodejs org directly and add to the team.

**Comment by maddhruv** [comment]
@JohnTitor we (me and @zeke) both don't have the rights to invite you to the org

without that, we can't add you to the team

cc @bnb can you invite her to the Nodejs Org and add to the i18n team?

**Comment by JohnTitor** [comment]
Ah, I didn't know that, sorry.

**Comment by JohnTitor** [comment]
ping @bnb what about?

**Comment by maddhruv** [comment]
@amiller-gh is also a part of i18n and can add you

**Comment by JohnTitor** [comment]
Ping @bnb @amiller-gh could you invite me to the Node.js org?

**Comment by JohnTitor** [comment]
I heard that @obensource might be able to do that - could you invite me to the Node.js org?

**Comment by JohnTitor** [comment]
I'd like to close this issue because a member sent me an invitation.
