### ISSUE TITLE
Help with German translations

### ISSUE THREAD

**Issue by NLDev** [nodejs/i18n#208]
Good Day! 

I'd like to offer help with the german translation of NodeJS and join the team. 
I was a bit confused because the [readme of the german NodeJS orga](https://github.com/nodejs/nodejs-de) states, the translation process is on hold. 
The [crowdin page](https://crowdin.com/project/nodejs/de#) however seems to be open for contributions. 
Is help on that subject needed (in terms of translation / proofreading)?

**Comment by alexandrtovmach** [comment]
@NLDev For sure you can start help with translation process here:
https://crowdin.com/project/nodejs/de

If you'd like to be a proofreader, let us know
