### ISSUE TITLE
Translate document in to Spanish

### ISSUE THREAD

**Issue by LuigiBaute** [nodejs/i18n#21]
HI! I would like to contribute to this project by offering a translation in to Spanish which is my native language. I work under the rules of Utopian-io and therefore I have to translate over a thousand words for it to be considered as a `contribution`.  Let me know if/when you guys are interested and I'll gladly start working with you. CHEERS! :+1:

**Comment by RichardLitt** [comment]
Hi @LuigiBaute. Thanks for the offer. We'll bring this up at the next i18n meeting. 

However, just to set expectations; I don't think we're interested in a quick translation of the document here, without some sense of upkeep. Translations for Markdown files on GitHub can go out of date very fast, and if you're only looking for a quick reward via Steem, this may not be the best project for you to contribute to. We also haven't yet had an expressed need for a Spanish translation, although I'm aware how ironic this is given that this is the i18n committee. 

If by this project you mean node - and not just this repository - we may need a translation, yes! We'll discuss this and post here after. Thanks again.

**Comment by alejandronanez** [comment]
I'm also interested in providing Spanish translations! I'll wait for more info about it in this issue :)

@RichardLitt is there any other repo I can contribute to with Spanish translations?

Thanks!

**Comment by RichardLitt** [comment]
@alejandronanez I'm not sure at the moment! I would follow along with the discussions in this repo about CrowdIn.

**Comment by obensource** [comment]
Closing https://github.com/nodejs/i18n/issues/62 should resolve this issue.

**Comment by zeke** [comment]
Resolved by #74 and #75 🎉

We have a new [getting started guide](https://github.com/nodejs/i18n/blob/master/GETTING_STARTED.md).

If all goes well during next week's [meeting](#79), we'll have content ready to translate at [crowdin.com/project/nodejs](https://crowdin.com/project/nodejs) by next week 🤞
