### ISSUE TITLE
Update the CONTRIBUTING.md & GETTING_STARTED.md guides

### ISSUE THREAD

**Issue by obensource** [nodejs/i18n#210]
## Description
Essentially, we don't have a contributing guide, and should extrapolate our getting started guide. We need clear documentation that enables participants to get involved in all major aspects of this initiative:
* How to join the i18n WG, and get involved in the initiative.
* How to work on the i18n repo to localize content coming from Crowdin.
* How to join Crowdin and localize Node.js resources as a translator.
* How to get involved in contributing to Intl in Node.js.
* How to gather volunteers to help out with all aspects of this initiative.

This, along with steady contributions from the i18n WG, will foster a *lot* of progress for Node.js i18n. 🎉

**Comment by srl295** [comment]
modify  https://github.com/nodejs/i18n/issues/210 per today;'s discussion

**Comment by RichardLitt** [comment]
Note from today's call: Neither I nor @zeke have the time to do this right now, but we'd love to see this move forward if anyone wants to take a stab at a first draft!

**Comment by alexandrtovmach** [comment]
Closed in favor #266 #270
