### ISSUE TITLE
Help with es locale i18n.

### ISSUE THREAD

**Issue by dags** [nodejs/i18n#212]
Hi,
let me know how could I help on 'es' i18n, if help is needed.

Regards,
Diego.

**Comment by nschonni** [comment]
Ping @nodejs/nodejs-es

**Comment by alexandrtovmach** [comment]
@dags For sure you can start help with translation process here:
https://crowdin.com/project/nodejs/es

If you'd like to be a proofreader, please check this:
https://github.com/nodejs/i18n/blob/master/GETTING_STARTED.md#proofreading
