### ISSUE TITLE
l10n (Spanish)

### ISSUE THREAD

**Issue by a0viedo** [nodejs/i18n#213]
Hi there! 👋

Thanks for moving forward the initiative and I'm happy to facilitate more people into translating content. My goal would be to keep this [repo](https://github.com/nodejs/nodejs-es) up-to-date with relevant information and possibly add people to the @nodejs/nodejs-es team. I wanted first to ask a few things I struggled to understand so that we can work on a better CONTRIBUTING.MD.

- **source of truth**: I saw crowdin is being used and seems really nice, my question would be if every changes that are reflected automatically into https://github.com/nodejs/i18n/tree/master/content/v10.x/es-ES/doc or there's a PR someone can comment on the changes then merge
- **content on the website**: if I select PT-BR as language on the website and go to the Guides section, even though those are translated the links point to the English versions (screenshot below)
![image](https://user-images.githubusercontent.com/2440935/74785625-78dd7d00-5289-11ea-95f2-29be72ef54e6.png)
Is this because a website pending change? Is it something the localization team should tackle?

It would also be great to hear from your experiences if there were people able to contribute without having to deal with any GitHub-related tasks.

**Comment by alexandrtovmach** [comment]
@a0viedo Thank you for your help with translation process!
> Is this because a website pending change? Is it something the localization team should tackle?
Yes, it should be handled by localization team, and it's coming soon (I hope)

related #100
