### ISSUE TITLE
i18n & l10n team collaboration best practices guide

### ISSUE THREAD

**Issue by obensource** [nodejs/i18n#214]
## Description
In addition to updating our basic contributing guides, it would behoove us to craft a best practices guide for collaborating with all localization teams. This should identify the common areas and patterns where the i18n WG and l10n teams can help enable and strengthen each other. These areas can then become ongoing aspects of team maintenance, allowing members of this WG and of l10n teams to know how and what to check in on periodically to maintain progress.

## Examples
* A l10n team dashboard for i18n WG members to reference for funneling interested translators to the right team, champions, and Crowdin project.
* An outreach template that gives i18n & l10n team members a simple track for asking for translation help (eg. on social media), and steps to getting them involved with the right teams.
* A FAQ sheet for i18n and l10n teams.

## We don't know enough about each other yet
We'll be discussing more of this topic today in our working group meeting, but we'd like to know more about what l10n teams need to feel supported, and what questions l10n teams have for the i18n working group right now. Please feel free to use this issue as a starting point if you're a part of either group and you'd like to touch base! 🙏

**Comment by RichardLitt** [comment]
Just to clarify:

## We'd like to know more about what l10n teams need to feel supported, and what questions l10n teams have for the i18n working group right now.

**Comment by alexandrtovmach** [comment]
Closing in favor #270
