### ISSUE TITLE
i18n WG Meeting - Feb 21

### ISSUE THREAD

**Issue by obensource** [nodejs/i18n#215]
### Date & Time
- 6:00pm UTC on Feb 21, 2020

### Links
- [Zoom link](https://zoom.us/j/307660555)
- [Google Docs Minutes](https://docs.google.com/document/d/1rsiTgkOp4GH2hf6LV8c1o1UBozTtViTCTmQek6lexrs/edit?usp=sharing)

#### l10n
- i18n & l10n best practices guide - https://github.com/nodejs/i18n/issues/214
- Update the contributing and getting started guides - https://github.com/nodejs/i18n/issues/210
- Audit of our l10n groups - https://github.com/nodejs/i18n/issues/19
- i18n WG Meeting Time & Frequency - https://github.com/nodejs/i18n/issues/34

#### i18n
- Unblock translation process - https://github.com/nodejs/nodejs.org/issues/2906
- website content to be translated - https://github.com/nodejs/i18n/issues/72
- Publish a module to npm - https://github.com/nodejs/i18n/issues/92
- automatic approve and merge translation PRs - https://github.com/nodejs/i18n/issues/161
- Create Crowdin Glossary - https://github.com/nodejs/i18n/issues/81 / https://github.com/nodejs/i18n/pull/91

#### Intl
* Onboarding new Intl contributors (not yet an issue)
  * What kind of help is needed the most in Intl right now?

**Note: Please feel free to add any issues you'd like to discuss today.** 👍

### Invited Members
- @nodejs/i18n 
- @nodejs/website-redesign 
- @nodejs/community-committee 
- @nodejs/tsc 
- @nodejs/website

**Comment by obensource** [comment]
Sorry I'm posting this at the last minute. But I feel it's better just to continue to create consistency in this working group regardless, rather than wait another week. 👍

No problem if you can't join, please feel free to post any thoughts or questions you have here. We'll be meeting at the same time next week. 🎉

**Comment by alexandrtovmach** [comment]
Will join in a 20 minutes

**Comment by obensource** [comment]
@srl295 @RichardLitt – would love to have you with us now if you're able to join, but no worries either way! 🎉

**Comment by sam-github** [comment]
If anybody in the WG wants to take on sorting https://github.com/nodejs/TSC/issues/813 out, I'd sure appreciate it!

**Comment by srl295** [comment]
@obensource sorry, conflict today, keep me invited!

**Comment by obensource** [comment]
## Calendarizing all the things! 🎉
@nodejs/i18n Hi y'all! I'm setting up our recurring meeting on the calendar right now. If you'd like a recurring calendar invite, would you please send me your email address directly?

🐦: twitter.com/obensource (DMs)
📧: benpmichel@gmail.com
🔑: keybase.io/obensource (encrypted messaging)

![online users](https://user-images.githubusercontent.com/1910457/75189324-caab5a80-5702-11ea-9a66-4f576883b42f.gif)

Thanks y'all! Excited to see you on the regular! 🍻

**Comment by a0viedo** [comment]
Thanks for organizing the meeting @obensource! Forgot to mention that I can't see 12x in crowdin for Spanish translations:
![image](https://user-images.githubusercontent.com/2440935/75197530-39a5a500-573d-11ea-8f99-3d686775926f.png)
Who has permissions to create that resource?

**Comment by alexandrtovmach** [comment]
@a0viedo for now we haven't connected to Crowdin correctly and going to fix that in near future

**Comment by alexandrtovmach** [comment]
@obensource Did you have a chance to see this issue https://github.com/nodejs/i18n/issues/216
