### ISSUE TITLE
CrowdIn Badge for percentages of translations

### ISSUE THREAD

**Issue by RichardLitt** [nodejs/i18n#218]
It'd be great to have these! 🙌🏽

I'm not sure if these should be on every repo, or only on this repo, or on the website. However, as a first step - let's get a way to show the badges as percentages. 

### To Do:
- [ ] Find the link for having translations percentages as a badge
  - [ ] Open a link to the CrowdIn page and explaining how to get these
- [ ] Figure out the percentages of CrowdIn translations on our website, at the moment.
- [ ] Add these to the Website footer? Discuss with @nodejs/website-redesign.

**Comment by amorist** [comment]
I think this is a good idea.
https://www.electronjs.org/languages
![image](https://user-images.githubusercontent.com/14037268/75607758-5a06a280-5b35-11ea-8caf-8dc203c86022.png)

**Comment by alexandrtovmach** [comment]
@RichardLitt Thanks for that, we'll keep in mind this idea, but for now is too early to add this. firstly we need to configure the process and the invite translators to help us. We'll back in month or so, and yeah Crowdin providing us wiht this great badge for GitHub repo:

[![Crowdin](https://badges.crowdin.net/nodejs-website/localized.svg)](https://crowdin.com/project/nodejs)

**Comment by RichardLitt** [comment]
Excellent. Thank you, @alexandrtovmach. I look forward to hearing back!
