### ISSUE TITLE
record all i18n groups in Markdown in repo, and contact for people

### ISSUE THREAD

**Issue by srl295** [nodejs/i18n#219]
from i18n meeting last week:

- record all i18n groups in Markdown in repo, and contact for people

There are a lot of i18n groups, make sure there is a way to find them.

**Comment by srl295** [comment]
1. One idea is to create team locales-core and invite 'core' people to it. but that's more fragile.

2. Another idea is to move all of the teams (i.e. `nodejs-es`, `nodejs-ru`) under something - perhaps i18n or some other parent team , where discussion could happen.

**Comment by nschonni** [comment]
Doesn't cover the contact part, but you might want to look at https://github.com/nodejs/node-core-utils/blob/master/docs/ncu-team.md

**Comment by srl295** [comment]
Thanks, this is a good argument for using a team to manage the membership

**Comment by alexandrtovmach** [comment]
After some brainstorm I'd propose the structure:
- nodejs/crowdin-managers
  - nodejs/crowdin-managers-api-docs
  - nodejs/crowdin-managers-website
  - nodejs/crowdin-managers-website-dev
- nodejs/translators
  - nodejs/nodejs-XX

Manager teams useful for project updates requests in issues, like "add language", "change permissions to proofreader"
Translator teams useful already, but we need to rearrange structure, and make one general team nodejs/translators, to make announcments for all translators community with one mention. For example, translation process of nodejs.org full migrated to Crowdin, and we need to ask all localization groups to change their docs and guides.

**Comment by alexandrtovmach** [comment]
I've made structure updates where I have access, and sent requests where haven't:
https://github.com/nodejs/TSC/issues/845

Waiting for approvals from TSC

**Comment by Trott** [comment]
The teams are already under `@nodejs/localization`. Would that be useable instead of `@nodejs/translators`? (I don't have an opinion. Just asking before doing anything. I'm not sure people know that all these teams are already a subteam of another team.)

**Comment by Trott** [comment]
The teams are already under `@nodejs/localization`. Would that be useable instead of `@nodejs/translators`? (I don't have an opinion. Just asking before doing anything. I'm not sure people know that all these teams are already a subteam of another team.)

**Comment by alexandrtovmach** [comment]
@Trott Good catch, but it should be renamed to `@nodejs/translators` anyway, because it's semantic correctly. Could you give me admin rights to [this team](https://github.com/orgs/nodejs/teams/localization), so I can change everything that we need

**Comment by Trott** [comment]
> @Trott Good catch, but it should be renamed to `@nodejs/translators` anyway, because it's semantic correctly. Could you give me admin rights to [this team](https://github.com/orgs/nodejs/teams/localization), so I can change everything that we need

@benjamingr What do you think? The idea here is to get rid of the (I believe just-created and unused) @nodejs/translators team, rename @nodejs/localization to @nodejs/translators, and make @alexandrtovmach a maintainer of the team (along with you, the only maintainer as of now) so that Crowdin set up can be completed.

**Comment by JoseJPR** [comment]
Hi all, I have only been here a short time but I would like to give my opinion. :)

I think the @nodejs/translators group is more successful than @nodejs/localization. The word "translators" correctly describes the group as people translating instead of "localization" which refers to locations.

**Comment by alexandrtovmach** [comment]
[New structure](https://github.com/nodejs/i18n/issues/219#issuecomment-607806363) is done
