### ISSUE TITLE
i18n WG Meeting - March 6th

### ISSUE THREAD

**Issue by obensource** [nodejs/i18n#222]
### Date & Time
* 6:00pm UTC on March 6, 2020

### Links
* [Zoom link](https://zoom.us/j/307660555)
* [Google Docs Minutes](https://docs.google.com/document/d/1_X3Ybw5nRC8vKU2zfcValo-Kj0y76GpAfYEMJtGUaS0/edit?usp=sharing)

### Agenda

Please feel free to add or subtract issues as is relevant. 👍

#### l10n
* l10n team structure mirroring Crowdin roles: Owners (l10n team champions), Reviewers, Translators (not an issue yet, but worth discussing).
* Localization best practices guide, #214
* Update our Guides, #210
* Create Crowdin Glossary, #81, #91

#### i18n
* Unblock translation process, [#2906](https://github.com/nodejs/nodejs.org/issues/2906)
  * Do we need to create another [special Node.js Github User](https://github.com/nodejs/i18n/issues/57), configure the @nodejs-crowdin bot to handle multiple tokens via crowdin (is that possible), or migrate to using the @nodejs/github-bot ?
* Publish a module to npm, #92
* Website content to be translated, #72
* Automatic approve and merge translation PRs, #161

#### Intl
* Onboarding new Intl contributors (not yet an issue)
  * What kind of help is needed the most in Intl right now?

**Note: Please feel free to add any issues you'd like to discuss today.** 

### Invited Members
* @nodejs/i18n
* @nodejs/website-redesign
* @nodejs/community-committee
* @nodejs/tsc
* @nodejs/website

**Comment by obensource** [comment]
@nodejs/i18n hi all! 👋 Unfortunately, I'm not going to be able to make this meeting. Can someone volunteer to facilitate it for me today? I can get you the zoom credentials for running it if you need. Thanks a million in advance! 🙏

**Comment by alexandrtovmach** [comment]
@obensource I can help, let's chat in slack

**Comment by obensource** [comment]
@alexandrtovmach awesome! Thanks so much for your help! If you wouldn't mind facilitating, maybe @bnb can help to start the meeting if he's free since there's an additional layer of access needed to start the YouTube steam. Can you lock that off today for us @bnb if you're available at all?

**Comment by bnb** [comment]
I can do it 👍

**Comment by obensource** [comment]
Thanks a million @bnb, really appreciate it! 🙏

**Comment by obensource** [comment]
@nodejs/i18n hey y'all, how'd it go? I noticed the meeting didn't make it to YouTube, we're y'all able to record it?

**Comment by alexandrtovmach** [comment]
We're done early because no one on the call, and here's record:
https://www.youtube.com/watch?v=pwau6gzooxo

**Comment by RichardLitt** [comment]
I also missed it! @obensource same time this week?

**Comment by RichardLitt** [comment]
Closing this.
