### ISSUE TITLE
Use node-release NPM package for supported versions

### ISSUE THREAD

**Issue by nschonni** [nodejs/i18n#246]
Been playing with this a bit https://www.npmjs.com/package/node-releases
It's just published copies of the index and release schedule from the NodeJS releases.
This would replace the hardcoded versions in https://github.com/nodejs/i18n/blob/05ea21d5f84805806a5f77e23654156804462915/package.json#L5-L8

There is some examples on how this package can  be leveraged over in BrowserList https://github.com/browserslist/browserslist/blob/65722d3d37b93ee5713164c766931d8332c53cde/index.js

**Comment by zeke** [comment]
Interesting.

So are you thinking we'd have some code that checks the dates in https://github.com/chicoxyzzy/node-releases/blob/master/data/release-schedule/release-schedule.json, compares to the current date, and produces a list of currently supported versions?

**Comment by nschonni** [comment]
Yup, that's the idea. Opened an issue over there to see if they'll expose a module for the data, instead of doing the JSON file requires

**Comment by alexandrtovmach** [comment]
I wouldn't like to use external package for this goal. If you can check - it's not up to date, and data in this module seems like updating manually. And it's also a bit weird to use this flow:

`i18n -> node-releases -> node`

instead of:

`i18n -> node`

**Comment by zeke** [comment]
I think this was replaced by https://github.com/nodejs/i18n/pull/281 and be closed. Is that correct?

**Comment by nschonni** [comment]
No, this would still have the advantage of pulling based on supported versions. The current approach is still a hardcoded static list of majors

**Comment by alexandrtovmach** [comment]
I'm not sure that I can understand what is the advantage. It's the same functionality as we already have in `master`. @nschonni could you explain?

**Comment by alexandrtovmach** [comment]
Current approach using predefined list of major versions, to be able to turn on/off targets, but minor and patch automated and pulling the latest version every night. Probably I misunderstood something from your idea, please let me know

**Comment by alexandrtovmach** [comment]
Closed in favor #281
Feel free to reopen, if there are any objections
