### ISSUE TITLE
i18n WG Meeting - March 20th

### ISSUE THREAD

**Issue by RichardLitt** [nodejs/i18n#247]
### Date & Time
* 6:00pm UTC on March 20, 2020

### Links
* [Zoom link](https://zoom.us/j/307660555)
* [Google Docs Minutes](https://docs.google.com/document/d/1_X3Ybw5nRC8vKU2zfcValo-Kj0y76GpAfYEMJtGUaS0/edit?usp=sharing)

### Agenda

Please feel free to add issues as is relevant. 👍 

@RichardLitt: The items below were copied from the last agenda.

- l10n team structure mirroring Crowdin roles: Owners (l10n team champions), Reviewers, Translators (not an issue yet)
- Localization best practices guide
- Update our Guides, #210
- Create Crowdin Glossary #230 and #231
- Publish a module to npm
- Onboarding new Intl contributors
  - What kind of help is needed the most in Intl right now?

#### l10n
TBD.

#### i18n
TBD.

#### Intl
TBD.

**Note: Please feel free to add any issues you'd like to discuss today.** 

### Invited Members
* @nodejs/i18n
* @nodejs/website-redesign
* @nodejs/community-committee
* @nodejs/tsc
* @nodejs/website

**Comment by RichardLitt** [comment]
I regret to say that I will be unable to make this today.

**Comment by bnb** [comment]
I will be starting the meeting off 👍

**Comment by srl295** [comment]
still on another meeting…

**Comment by designMoreWeb** [comment]
Still in another meeting

**Comment by alexandrtovmach** [comment]
@zeke And could you also create one more project on Crowdin and give me manager access. Thank you 👍

**Comment by zeke** [comment]
We tried to connect https://crowdin.com/project/nodejs-website to https://github.com/nodejs/nodejs.dev today but discovered that the @nodejs-crowdin user doesn't have the necessary access to that repository. I opened an issue here: https://github.com/nodejs/i18n/issues/248

**Comment by zeke** [comment]
> could you also create one more project on Crowdin 

@alexandrtovmach sure. What should I name it?

**Comment by alexandrtovmach** [comment]
nodejs-website-dev ?

**Comment by nschonni** [comment]
@alexandrtovmach can you point https://crowdin.com/project/nodejs-website at  https://github.com/nodejs/nodejs.org

**Comment by alexandrtovmach** [comment]
@nschonni of course, but it's blocked by #248

**Comment by alexandrtovmach** [comment]
> ### Date & Time
> * 6:00pm UTC on March 20, 2020
> 
> ### Links
> * [Zoom link](https://zoom.us/j/307660555)
> * [Google Docs Minutes](https://docs.google.com/document/d/1_X3Ybw5nRC8vKU2zfcValo-Kj0y76GpAfYEMJtGUaS0/edit?usp=sharing)
> 
> ### Agenda
> Please feel free to add issues as is relevant. 👍
> 
> @RichardLitt: The items below were copied from the last agenda.
> 
> * l10n team structure mirroring Crowdin roles: Owners (l10n team champions), Reviewers, Translators (not an issue yet)
> * Localization best practices guide
> * Update our Guides, #210
> * Create Crowdin Glossary #230 and #231
> * Publish a module to npm
> * Onboarding new Intl contributors
>   
>   * What kind of help is needed the most in Intl right now?
> 
> #### l10n
> TBD.
> 
> #### i18n
> TBD.
> 
> #### Intl
> TBD.
> 
> **Note: Please feel free to add any issues you'd like to discuss today.**
> 
> ### Invited Members
> * @nodejs/i18n
> * @nodejs/website-redesign
> * @nodejs/community-committee
> * @nodejs/tsc
> * @nodejs/website
