### ISSUE TITLE
Requesting access to website repos for @nodejs-crowdin GitHub user

### ISSUE THREAD

**Issue by zeke** [nodejs/i18n#248]
@nodejs-crowdin is the GitHub user we use to integrate Crowdin with this GitHub repository (nodejs/i18n).

We'd also like to be able to integrate Crowdin with the following repos:

- [x] https://github.com/nodejs/nodejs.org https://github.com/nodejs/nodejs.org/issues/3031
- [x] https://github.com/nodejs/nodejs.dev https://github.com/nodejs/nodejs.dev/issues/438

Not exactly sure which team(s) to ping for assistance on this...

cc @nodejs/i18n @alexandrtovmach 

![Screen Shot 2020-03-20 at 10 32 38 AM](https://user-images.githubusercontent.com/2289/77192630-151dbe00-6a9a-11ea-8041-705d3fafa9ba.png)

**Comment by nschonni** [comment]
I'd suggest opening issues on the individual repos. The teams to ping are problably `website` and `website-redisign` but opening issues there would be better to track the requests and scope of the permission.

**Comment by zeke** [comment]
Thanks @nschonni. I've opened issues on those two repos:

- https://github.com/nodejs/nodejs.org/issues/3031
- https://github.com/nodejs/nodejs.dev/issues/438

**Comment by zeke** [comment]
☝️ I've updated the OP here with a checklist. `nodejs.org` is set up. Still waiting on `nodejs.dev`

**Comment by alexandrtovmach** [comment]
website-redesign team already give access to their repo, @zeke could you try to integrate?

**Comment by alexandrtovmach** [comment]
@zeke Could you also set sync schedule interval for all projects to 24 hours?
https://support.crowdin.com/github-integration/#synchronization-schedule

**Comment by zeke** [comment]
> set sync schedule interval for all projects to 24 hours

- [ ] https://crowdin.com/project/nodejs-website-dev/settings#integration (pending https://github.com/nodejs/nodejs.dev/issues/438)
- [x] https://crowdin.com/project/nodejs-website/settings#integration
- [x] https://crowdin.com/project/nodejs/settings#integration

**Comment by zeke** [comment]
nodejs.dev Crowdin integration is now set up: https://github.com/nodejs/nodejs.dev/issues/438#issuecomment-613055614

All three projects are now on a 24-hour sync schedule. 📆

**Comment by alexandrtovmach** [comment]
@zeke Amazing news, thank you for help
