### ISSUE TITLE
Request to join the group

### ISSUE THREAD

**Issue by okuryu** [nodejs/i18n#249]
Hi there,

Can I join this project as a member? I can help with something related to Japanese. I'm also a member of [nodejs-ja](https://github.com/orgs/nodejs/teams/nodejs-ja/members) team.

**Comment by zeke** [comment]
Hi @okuryu 👋 Thanks for your interest. We'd love to have you.

Can you open a pull request to add yourself to this README? https://github.com/nodejs/i18n#current-members

**Comment by okuryu** [comment]
I just created a PR.
