### ISSUE TITLE
Request to join i18n WG

### ISSUE THREAD

**Issue by lukaszewczak** [nodejs/i18n#25]
Hi, I'm from Poland and I'm interested in contributing to nodejs. I do not have to much experience witch internationalization and open source in general, but I would like help this group in achieving their goals. So if you are able to accept not too experienced person, which want to develop their skills it would be great :-), if not at the moment, then maybe I could help with polish translations.

Regards

**Comment by obensource** [comment]
@lukaszewczak thank you for reaching out and offering to help! We're more than happy to have you with us, and given that this initiative is relevant to your interests–I agree that it would be a great place for you to start and get involved! 🎉

I think the best thing you can do to help us help you grow here–is communicate *early* and *often* about where you'd like to jump in. The more experienced members among us can help you navigate where to help out as you go!

In general, the work we have ahead of us will be divided between more logistical work–like communicating across our localization teams who're doing translation into their own languages, and discussing & creating code repositories that will implement how we get those translations into where Node.js needs them.

You should feel free to jump in anywhere you'd like, and if you're not sure about where you can fit in–create more issues, or reach out to anyone here and our team will be more than happy to help. 👍

For now, I suggest joining us in our [upcoming WG meeting](https://github.com/orgs/nodejs/teams/i18n/discussions/1) as we all get more familiar with our awesome team and discuss all this. Thanks for your interest, and welcome @lukaszewczak!

**Comment by obensource** [comment]
@lukaszewczak added you to our members list. Closing your issue. 👍

**Comment by lukaszewczak** [comment]
Great :-) ! Thank you @obensource !  Where I can found those localization teams you mentioned?

**Comment by RichardLitt** [comment]
Welcome, @lukaszewczak!
