### ISSUE TITLE
Mark 8.x as low priority like 6.x

### ISSUE THREAD

**Issue by nschonni** [nodejs/i18n#253]
Since 8 has reached EOL, it should probably get marked as a low priority like the 6.x folder was

**Comment by alexandrtovmach** [comment]
Done
![image](https://user-images.githubusercontent.com/28801003/77707859-19346900-6fcf-11ea-9b9d-a7ed8b9fb106.png)

**Comment by nschonni** [comment]
Thanks, I'll remove it from the collect setup after the last sync is done in the other PR
