### ISSUE TITLE
👋 Hi, I would like to join this group.

### ISSUE THREAD

**Issue by JoseJPR** [nodejs/i18n#265]
Hi, my name is Pepe, I'm JavaScript developer and I have been working with NodeJS for about six years.

I would like to be able to contribute to this group and help with the translation of the documentation to Spanish language.

A few days ago I was working with the translation of the web nodejs.org as well.
https://github.com/nodejs/nodejs.org/pull/3047

Regards!!!

**Comment by alexandrtovmach** [comment]
Welcome @JoseJPR 
Nice to see you here and we appreciate any contribution. Please read our guide and feel free to join translation process on Crowdin:
https://github.com/nodejs/i18n/blob/master/GETTING_STARTED.md

**Comment by JoseJPR** [comment]
@alexandrtovmach Thank you! Now I'll use that via to collaborate with the translation. :)
