### ISSUE TITLE
Fix nightly sync

### ISSUE THREAD

**Issue by alexandrtovmach** [nodejs/i18n#272]
We need to update nightly build, because it seems like not working:
https://github.com/nodejs/i18n/actions?query=workflow%3A%22Nightly+Sync+of+content%22

@nschonni Do you have any idea?

Related: #242

**Comment by alexandrtovmach** [comment]
Code didn't catch error if nothing to commit, and fails. To not write new implementation, just replaced commit action code with [third-party module](https://github.com/marketplace/actions/add-commit). Please review #273

**Comment by alexandrtovmach** [comment]
Seems like fixed, let's see how it'll run this night:
https://github.com/nodejs/i18n/runs/575088458?check_suite_focus=true

@zeke Thanks for quick review
https://i.imgur.com/zqVblUG.gif

**Comment by zeke** [comment]
🎸

**Comment by alexandrtovmach** [comment]
Seems okay:
https://github.com/nodejs/i18n/runs/575859773?check_suite_focus=true
