### ISSUE TITLE
Request to become a proofreader on CrowdIn

### ISSUE THREAD

**Issue by BrsJsk** [nodejs/i18n#289]
Hi,
I'm working on translations for Serbian (Latin) and I've got around 1000 words translated now(Screenshot attached).
I would like, if possible, to be promoted to a proofreader as currently there is none as Serbian (Latin) for API docs as it was added recently.
https://crowdin.com/project/nodejs/sr-CS#

Also, I'd like to join the i18n team of the Node,js organization if possible.

Screenshot
![](https://i.imgur.com/amp9A7i.png)

**Comment by JoseJPR** [comment]
Hi @BrsJsk,

FYI: the link open correctly if you copy and paste in the browser, if you click it does not lead to the screenshot.

**Comment by alexandrtovmach** [comment]
Thanks for your contributions
![image](https://user-images.githubusercontent.com/28801003/79155638-195ba380-7dda-11ea-9a17-214837e9f76f.png)
