### ISSUE TITLE
🔬 Request to be a Proofreader

### ISSUE THREAD

**Issue by JoseJPR** [nodejs/i18n#293]
Hi, after my presentation in this other issue (https://github.com/nodejs/nodejs.org/issues/3098).

I would also like to propose myself as Proofreader. And in this way you can review translations from other developers.

Currently, I have this PR (https://github.com/nodejs/nodejs.org/pull/3047) with several pages translated of website (nodejs.org) and, on the other hand, 1800 words translated into Crowdin. I share you a screenshot of the progress.

![Captura de pantalla 2020-04-13 a las 20 45 20](https://user-images.githubusercontent.com/28801003/79150466-7dc63500-7dd1-11ea-9a00-dcf974b4c536.png)

I hope it is enough and I can choose to be "Proofreader" 😋

Greetings from Spain :)

@nodejs/nodejs-es 
@nodejs/crowdin-managers-website

**Comment by alexandrtovmach** [comment]
Thanks for your contributions:
![image](https://user-images.githubusercontent.com/28801003/79155815-68a1d400-7dda-11ea-84f7-6c2e8e92f575.png)
