### ISSUE TITLE
Joining & Contributing

### ISSUE THREAD

**Issue by BrsJsk** [nodejs/i18n#298]
Hi all, I'd like to join the group and contribute to i18n.
I'm currently a proofreader for Serbian (Latin).

Thanks

**Comment by maddhruv** [comment]
hey, @BrsJsk you can go ahead with our [Getting Started Guide](https://github.com/nodejs/i18n/blob/master/guides/GETTING_STARTED.md) and easily get involved. Looking forward to your contributions :hugs:
