### ISSUE TITLE
Proposal: Let @RichardLitt Join i18n committee

### ISSUE THREAD

**Issue by RichardLitt** [nodejs/i18n#3]
After a few months away from collaborating Node, I am starting to miss the work. 

### Why Richard

I'm currently writing a thesis on resources for endangered languages - see [this repo](https://github.com/RichardLitt/thesis) - and I am interested in seeing if being a more active member of this group could help inform my own work, and if I can give back. I have an MA in Linguistics and am one thesis away from an MSc in Computational Linguistics. While I speak only English fluently, I can talk conversationally in seven other languages, and maintain several projects with translations. I wrote the dictionary for Na'vi from the movie avatar, and oversaw a community of five thousand learners and over a dozen different translations of the dictionary. 

On the Node side: I am a core contributor, have been around for around half a decade, have hosted NodeSchools in several countries (often the first in that city), have been a member of the Community Committee in the past, and I run an open source company based in a large part on my experiences in node. 

### What's next?

What do you need from me for this to move forward.

**Comment by rachelnicole** [comment]
@RichardLitt if you'd like to join just create a PR adding your name to the list and we'll start including you on future meetings & other correspondence. :D

**Comment by obensource** [comment]
@RichardLitt your thesis work is AMAZING! I can't wait to read more of it. Wonderful work! 👏👏👏

Thank you for sharing some of your background, it's really awesome to know more about you! 🙌

We are insanely stoked to have you with us. +1 to @rachelnicole, please PR yourself on the README, and I can also add you to our [i18n team](https://github.com/orgs/nodejs/teams/i18n).

Really looking forward to hang with you more in our meetings and such! 🎉

**Comment by RichardLitt** [comment]
Thanks @rachelnicole and @obensource :)

**Comment by RichardLitt** [comment]
Thank you!
