### ISSUE TITLE
Supported versions strategy

### ISSUE THREAD

**Issue by alexandrtovmach** [nodejs/i18n#310]
We removed v8.x (#263 ), and content folder become so empty 😰 
![image](https://user-images.githubusercontent.com/28801003/79615742-22b37b80-810c-11ea-8d11-76cb260011b8.png)

## Question:
Why do we have this system with limited scope of supported versions?
> I know, we already implement everything, and just now I start asking, but why not?

## My thoughts:
Later, when translated docs become online, what will be shown for older and odd versions?
![image](https://user-images.githubusercontent.com/28801003/79616481-d36e4a80-810d-11ea-89e0-571576cbba4f.png)

@nodejs/i18n 
@nodejs/i18n-api 

Crazy 🤯, but seems like we have logical issue, or I don't understand something

**Comment by zeke** [comment]
Early on in this project we decided to only support [LTS](https://github.com/nodejs/Release) and newer versions of Node.js. Translating older versions would not only add more work, more files, more needless translation, but we should also be discouraging people from building anything new with those old versions of Node.js

**Comment by alexandrtovmach** [comment]
Yeah, it makes sense, but if we have the dropdown with full list of versions on docs website I think it's more logical to have translated version for each of them

For me it's about priorities, not about removing content

**Comment by alexandrtovmach** [comment]
We can set priorities for translators, to keep they focused on target versions. But make hard remove already translated content for deprecated content, and as result hide it from the website - strange for me

**Comment by JoseJPR** [comment]
I have only been here a short time but I would like to contribute my point of view.

I think that content that already exists as versions 8, 7 etc and that already have translated content should continue offering their translations.

As long as the translators (as in my case) are clear that we should focus on specific versions, it would be sufficient.

**Comment by alexandrtovmach** [comment]
My idea that we should not limit our scope with "supported versions" and we should not remove any translated content. Instead, we can work with priorities to manage target versions for translators:
![image](https://user-images.githubusercontent.com/28801003/79637684-1a9a2100-818a-11ea-8be0-e029b40fc8b6.png)

From tech perspective, we'll continue using "supportedVersions" just in performance reasons - we don't need to fetch content for already dead versions:
![image](https://user-images.githubusercontent.com/28801003/79638010-f9d2cb00-818b-11ea-9f79-4cf9991b09af.png)

**Comment by alexandrtovmach** [comment]
The list of tasks to solve this:
- [ ] Update [Crowdin guide](https://github.com/nodejs/i18n/blob/master/guides/CROWDIN.md) with info about priorities
- [ ] Update tests to keep old versions
- [ ] Upload content for all versions (deprecated and odd) to the repo. Sync with Crowdin, pretranslate with TM, mark with Low priority
- [ ] Push pre-translated content from Crowdin to the repo

**Comment by alexandrtovmach** [comment]
@nodejs/i18n @nodejs/i18n-api Please check my comments and PRs

**Comment by TiagoDanin** [comment]
> but we should also be discouraging people from building anything new with those old versions of Node.js

Agree :+1:

My another preoccupation is we have many fragmented files. In no-LTS version most would be translated by pre-translated.
