### ISSUE TITLE
Document how content is published from this repo to nodejs.org

### ISSUE THREAD

**Issue by nschonni** [nodejs/i18n#315]
It's not clear in the documentation here how the content in this repo get onto the nodejs.org website. I don't see anything with a quick search of https://github.com/nodejs/build that would indicate it's getting pulled down.

I want to keep this separator from #310, but it may influence that direction. EX: if there is nothing publishing content outside of a manual release process, there is no point continuing translations for old content unless we can change that.

**Comment by alexandrtovmach** [comment]
Great question, about building process. I'm also don't know how it's working now, and my suggestion is going directly from nodejs/node repo with some `make` script. Unfortunately, I'm not confident with language that used for build scripts, so I can't investigate to be sure.

**Comment by alexandrtovmach** [comment]
> if there is nothing publishing content outside of a manual release process, there is no point continuing translations for old content unless we can change that

We need to understand build flow first, and then make decisions, but I think that docs for all versions builds everytime with a new release. Not sure that someone implements atomic build/deploy, because it's so hard and complicated for simple docs website.

**Comment by nschonni** [comment]
OK, going by the other issue on the build repo, it sounds like this content isn't being published anywhere right now

**Comment by alexandrtovmach** [comment]
@nschonni yeah, i18n docs never be live and we should figure out way to deliver it. What is our plan?

**Comment by alexandrtovmach** [comment]
Could you take a look on possible ways and try to implement it? I'm asking because don't want to duplicate work, again ;)

Let me know if it works for you and how can I help

**Comment by Trott** [comment]
I've unarchived this repo so I can close all PRs and issues before re-archiving.
