### ISSUE TITLE
Formatting translated content

### ISSUE THREAD

**Issue by alexandrtovmach** [nodejs/i18n#316]
We have some formatting issues with content after Crowdin translation (thanks @nschonni for pay attention) I'll take a look and keep posted here

related:
- https://github.com/nodejs/nodejs.org/pull/3108
- https://github.com/nodejs/nodejs.org/pull/3111
- https://github.com/nodejs/nodejs.org/pull/3112

**Comment by alexandrtovmach** [comment]
After investigation, I've figured out two issues with formatting:
1. Additional line at the end to file - **already fixed by Crowdin team**
2. Predefined links moved - **fix coming**

**Comment by obensource** [comment]
Looks good, glad Crowdin resolved it! 👍
