### ISSUE TITLE
Hide strings from translation

### ISSUE THREAD

**Issue by alexandrtovmach** [nodejs/i18n#318]
We have a content that shouldn't be translated:
- links
- names
- titles

related: https://github.com/nodejs/nodejs.org/pull/3112#discussion_r411473514

How it's possible with Crowdin you can find in this video ["How to single/mass hide strings"](https://www.youtube.com/watch?v=qQEZDdwLqyc&feature=youtu.be). And yeah, for now it's manual only 😉 

How do you think, does it okay to leave this process manual for managers? Or we can implement some script to do the same thing but from our _.json_ file?

I'm okay to keep it on Crowdin side, because with custom script we should think about a lot of stuff.

**Comment by bittlingmayer** [comment]
This is ideal for using machine translation effectively, and thus for #319.

**Comment by alexandrtovmach** [comment]
If there are no objections, I'm going to add note about manual strings hiding process, and will close this issue.

**Comment by bittlingmayer** [comment]
SGTM.

You can also do this automatically with ModelFront: those strings where when it's just copied it is < 1% risk.

https://modelfront.com/when-not-to-translate/#a-simple-heuristic

We already had URLs and source code, and we've added more .md and JavaScript to cover this type of content.

**Comment by Trott** [comment]
I've unarchived this repo so I can close all PRs and issues before re-archiving.
