### ISSUE TITLE
Node.js logo for Crowdin

### ISSUE THREAD

**Issue by alexandrtovmach** [nodejs/i18n#322]
I was approached by Crowdin marketing, they wanted to add Node.js to their customers' page
Just wanted to confirm we are OK to let them do that?

**Comment by alexandrtovmach** [comment]
@nodejs/i18n @nodejs/tsc

**Comment by RichardLitt** [comment]
Sounds fine to me.

**Comment by mcollina** [comment]
Unfortunately it's not that easy. I think we need to escalate this.

Please read: https://nodejs.org/static/documents/trademark-policy.pdf

**Comment by mcollina** [comment]
cc @nodejs/community-committee

**Comment by mhdawson** [comment]
I second @mcollina's comment. It would like need to get the ok from the Foundation.  in particular it guidelines say `And remember that you must avoid any use
that implies any endorsement of you or your site or otherwise by the Foundation.`

**Comment by alexandrtovmach** [comment]
How we can ask foundation?

**Comment by mhdawson** [comment]
@brianwarner can you help with who should be contacted for the request?

**Comment by alexandrtovmach** [comment]
Ping ping

**Comment by brianwarner** [comment]
Thanks, is there any more context on the request?  For example, specifics on how and where it's being used?

**Comment by alexandrtovmach** [comment]
@h-khrystyna Could you provide more details?

**Comment by h-khrystyna** [comment]
hi @brianwarner !

It would be great if we could feature Node.js as a customer on our website alongside GitHub, GitLab, Huawei, and other companies that use Crowdin.

We'd really love to add your logo to our customers page:
https://crowdin.com/page/customer-testimonials

**Comment by bnb** [comment]
FWIW my understanding is that they've comped us their services for free. If that's the case, I'd be +1 on enabling them to use our logo if it's possible to make happen (I know it's... a complex situation for us, unfortunately).

**Comment by alexandrtovmach** [comment]
@bnb Agree with you 👍 
@brianwarner Could you help with?

**Comment by brianwarner** [comment]
Yep! Sorry, I should have left an update. I have an open question with legal about this, given that there are unique considerations around the Node marks. I'll be back when I have an answer :-)

**Comment by comradekingu** [comment]
As a translator, using Crowdin is not good advertisement, to the contrary.
It is a platform that does tracked profiling, sells data to advertisers, and takes shared ownership in what is an accumulated closed source translation memory. It is a lackluster, and closed source tool, that only operates as a web-service platform, and also only provides gratis hosting for non-commercial libre software projects.
That is the head of Crowdin marketing pretending to be a developer in blogposts you are talking to btw.

**Comment by alexandrtovmach** [comment]
@brianwarner Any updates? Thanks

**Comment by brianwarner** [comment]
Hi, I'm sorry, I thought I'd replied on this. 

Legal reviewed the request, and based upon the scope of the Node trademark license to the Foundation, unfortunately we don't feel we can approve this.

**Comment by alexandrtovmach** [comment]
@brianwarner okay thanks :+1:
