### ISSUE TITLE
Repo contains content for disabled languages

### ISSUE THREAD

**Issue by zeke** [nodejs/i18n#325]
I wrote a script to gather stats for this project using the Crowdin API and noticed that these languages exist as content in this repo, but are not enabled in the [nodejs](https://crowdin.com/project/nodejs) project on Crowdin:

- `af-ZA` Afrikaans (South Africa)
- `ca-ES` Catalan (Spain)
- `sr-SP` Serbian (SP)

I'm guessing they were enabled at one time and have since been disabled?

I'm also guessing that we should open a PR to manually remove the content for these locales, unless @alexandrtovmach or @nschonni or someone else has recently added some automation to remove those extraneous files.

cc @nodejs/i18n

**Comment by nschonni** [comment]
If you don't think that a team is ready to step in to support them, you could run `git rm -rf content/*/af-ZA` to remove the files across all versions

**Comment by alexandrtovmach** [comment]
We haven't any script that doing that compare content in repo and Crowdin automatically, so I'm going to drop it manually with PR
