### ISSUE TITLE
i18n WG Meeting Time & Frequency

### ISSUE THREAD

**Issue by obensource** [nodejs/i18n#34]
## Time 🕓
I propose we hold a regular WG meeting every Tuesday at **4PM-5PM UTC**. – It would seem that time might work for the majority of us (or at least I hope). 

## Frequency ∿
Should we follow the standard Node.js WG pattern and maintain a weekly meeting?

I imagine meeting weekly will be beneficial over the spring and maybe beyond while we're doing a lot of implementation. I suppose we can opt to meet bi-weekly if we perceive that to be best at any point.

**Comment by lukaszewczak** [comment]
As for me, it suits me better at **3PM UTC** at 4PM UTC I'm usually on the train on the way home. :-) Weekly meeting will be enough to start.

How much time do you expect for such a meeting? 
Are those meetings will be recorded and available on youtube as meetings from other working groups?

**Comment by obensource** [comment]
@lukaszewczak oh right, an end-time would be helpful lol. I'll add that now. Thanks for sharing your availability.

Yes, we should probably set up a YouTube recording stream like other working groups. I think it's fairly seamlessly integrated with Zoom.

**Comment by RichardLitt** [comment]
I don't believe there was consensus during the call about the best time to hold the meetings, as I missed the bit where we may have gotten to it at the end. For now, can I tentatively suggest March 20th at 3PM UTC, to accommodate @lukaszewczak?

**Comment by laosb** [comment]
For Chinese members, 4PM - 5PM Tuesday UTC === 0AM - 1AM Wednesday CST. That doesn't sound very good actually.

**Comment by obensource** [comment]
I think it would be advantageous for us to select an ongoing meeting time that works for everyone as soon as we can, so we can depend on it regularly.

I know there is simply no perfect time for everyone since our i18n members are distributed across most continents, but I'll place a couple suggested times here in the hope that we can find a general consensus with one. If none of these will work, we can try for other time suggestions too. 🍻

### Suggested Meeting Times
*eg. PST: Pacific Standard Time, CET: Central European Time, CST: China Standard Time*

* **5:00 UTC**
  * **PST**: 10pm-11pm
  * **CET**: 6am-7am
  * **CST**: 1pm-2pm

* **13:00 UTC**
  * **PST**: 6am-7am
  * **CET**: 9pm-10pm
  * **CST**: 2pm-3pm

* **14:00 UTC**
  * **PST**: 7am-8am
  * **CET**: 10pm-11pm
  * **CST**: 3pm-4pm

**Comment by RichardLitt** [comment]
I'm on EST, and can't do 5:00 UTC because that's pretty darn late. 1300 and 1400 work better for me.

**Comment by vanessayuenn** [comment]
Perhaps we can agree on two meeting times, one good for CST, and one good for PST (CET sort of sits in the middle so we should be good), and alternate between the two? That way most of us can at least attend every other meeting.

**Comment by obensource** [comment]
@vanessayuenn brilliant! That sounds awesome! 🍻

**Comment by laosb** [comment]
@vanessayuenn Sounds good. Anyway, much of my spare time this semester is 5:30AM - 8:00AM and later than 4:00PM CST, due to my tight class schedule.

**Comment by FranzDeCopenhague** [comment]
14:00 UTC works for me too

**Comment by laosb** [comment]
@obensource I suddenly notice that your CST - UTC conversion is not correct. CST is 8 hours ahead of UTC, which means:

- 13:00 UTC === 21:00 CST
- 14:00 UTC === 22:00 CST

**Comment by RichardLitt** [comment]
This all may change in a couple of weeks, too, but I'm not sure. Right now we are in the evil America does not match Europe Daylight Savings timegap.

**Comment by lukaszewczak** [comment]
13:00 UTC and 14:00 UTC works for me but it seams that 13:00 UTC === 14 CET

**Comment by amor520** [comment]
13:00 UTC and 14:00 UTC works for me too

**Comment by laosb** [comment]
Update: as a member of the student union, I will need to have regular meetings every week on 13:00 UTC. I'm afraid that Tuesdays won't work for me.

**Comment by RichardLitt** [comment]
I'm not sure if I missed the last meeting, on Tuesday; we're having one this next Tuesday, correct? It sounds like 1400 UTC might be a good time for the next meeting.

**Comment by RichardLitt** [comment]
Ok, I am clearly missing something, or we're just not meeting at the moment. It's a bit too late for today's meeting.

I'm opening a new issue to track next week's meeting on Tuesday at 1400UTC.

**Comment by obensource** [comment]
@RichardLitt I'm very sorry for the confusion. The missing piece is that we finalized a meeting day, but not a time. I will be clearing that up today.

**Comment by RichardLitt** [comment]
@obensource We shouldn't have to rely on you to push things forward, and there's no need to apologize. I've set up an issue and specified a time based on conversation here. I think all we need is the spark to get things going. 

Let me know if you think that's the wrong approach! Just trying to get cats in a room. :)

**Comment by obensource** [comment]
Thanks @RichardLitt. Absolutely true. 

Thanks for https://github.com/nodejs/i18n/issues/64, time to get the spark going and make it happen. 😎

After this meeting, I think it might be most beneficial to oscillate between two times that would be ideal for people in CST & PST respectively, as proposed earlier by @vanessayuenn.

We also connect with @mhdawson and see if we can use his automated meeting-issue generator that's been working well for CommComm and elsewhere in Node.js (eg. https://github.com/nodejs/community-committee/issues/287)

**Comment by obensource** [comment]
We can verify and nail down our reoccurring time & dates tomorrow at our next WG meeting! 🙌

@bnb once we do that–we'd love to get them on the calendar! :D

**Comment by maddhruv** [comment]
Anyone syncing the minute docs?? :worried:

**Comment by laosb** [comment]
Sounds like no one synced the minute docs. I would try simply put the incomplete notes from Google Docs into a PR if no one does it yet.

**Comment by zeke** [comment]
☝️ https://github.com/nodejs/i18n/pull/73

**Comment by obensource** [comment]
@nodejs/i18n bumping this. Let's plan on picking back up with regular meetings on 6/18. I'm going to throw out 2pm UTC (7am PST / 16:00 CEST) as the targeted time. Let me know if y'all have any hard conflicts with that, or would like to propose another time. 🙌

**Comment by obensource** [comment]
@nodejs/i18n I'll get this on the Node.js calendar asap, but for now let's track this [calendar event](https://calendar.google.com/event?action=TEMPLATE&tmeid=M3NrajZrdTFoYzZhNWZ2anI4b2Flam40aGogYmVubWljaGVsQGludmlzaW9uYXBwLmNvbQ&tmsrc=benmichel%40invisionapp.com). 🗓

**Comment by maddhruv** [comment]
can be closed as we already are lined up with scheduled recurring meetings

**Comment by AugustinMauroy** [comment]
the discussion are reopen [Here](https://github.com/nodejs/i18n/issues/735)
