### ISSUE TITLE
Issue: i18n WG Meeting May 22, 2020

### ISSUE THREAD

**Issue by alexandrtovmach** [nodejs/i18n#340]
### Date & Time
* 6:00pm UTC on May 22, 2020

### Links
* [Zoom](https://zoom.us/j/307660555)
* [Google Docs Minutes](https://docs.google.com/document/d/1996iPZqy_hVjiphgiICaDQZXg9ZU42QSdrkd6l1gS00)

### Agenda

> Note: Please feel free to add any issues you'd like to discuss today 👍

### Invited Members
* @nodejs/i18n
* @nodejs/i18n-api
* @nodejs/website-redesign
* @nodejs/community-committee
* @nodejs/tsc
* @nodejs/website

**Comment by alexandrtovmach** [comment]
@obensource @bnb Could someone start a call today?

**Comment by obensource** [comment]
@alexandrtovmach jumping back in today! 🙌

I can start the call, np. 👍

See y'all in a bit! 🚀

**Comment by srl295** [comment]
me too… on the zoom link?

**Comment by alexandrtovmach** [comment]
@srl295 yep, zoom link from the issue in 40 minutes

**Comment by srl295** [comment]
cool. I have a conflict for the first :15 then, but then will join!
--
Steven R. Loomis | @srl295 | git.io/srl295

**Comment by bnb** [comment]
just got off of a meeting to onboard @zeke to zoom as well, fwiw 👍

**Comment by alexandrtovmach** [comment]
@bnb Thank you, it's really helpful 👍
