### ISSUE TITLE
Node.js i18n WG Meeting 2018-03-06

### ISSUE THREAD

**Issue by obensource** [nodejs/i18n#37]
## Time
UTC Tue 06-March-2018 16:00 (04:00 PM)
[What is 4PM-UTC In your local time?](http://www.wolframalpha.com/input/?i=04PM+UTC,+March+06,+2018+in+local+time)

## Links
* [Minutes Google Doc](https://docs.google.com/document/d/1daZuYpjomqVylkpNJ2TDLa3Gjd-3KvrNpMBkpwxNlOQ)

## [Current Members](https://github.com/nodejs/i18n#current-members)
@amiller-gh (Adam Miller)
@toinane (Antoine Olivier)
@obensource (Ben Michel)
@tiriel (Benjamin Zaslavsky)
@maddhruv (Dhruv Jain)
@JCMais (Jonathan Cardoso Machado)
@lukaszewczak (Łukasz Szewczak)
@rachelnicole (Rachel White)
@rajzshkr (Raja Sekar)
@RichardLitt (Richard Littauer)
@ryo-a (Ryo.A)
@sotayamashita (Sam Yamashita)
@srl295 (Steven R. Loomis)
@tiagoDanin (Tiago Danin)
@vanessayuenn (Vanessa Yuen)
@volem (Volkan Nazmi Metin)
@zeke (Zeke Sikelianos)

### General Logistics
* [#34: WG meeting time & Frequency](https://github.com/nodejs/i18n/issues/34)
* [#30: Translators for our WG meetings](https://github.com/nodejs/i18n/issues/20)
* Regular WG meeting issue owner (generate issues for our i18n WG meetings)?
* Regular WG Meeting minutes taker?

### Reports
* [#36: Initial i18n team meeting with Crowdin](https://github.com/nodejs/i18n/issues/36)
* ECMA-402 & Unicode Standards update (ICU, CLDR) - @srl295
* Anything else?

### Current Initiatives
* [#19: Audit of our l10n groups](https://github.com/nodejs/i18n/issues/19)
* Getting our i18n module going & what we can build right now (Outcome: generate an issue)
* Crowdin Integration (Outcome: generate an issue)

## Joining the meeting
* Video call link will be provided for participants a few minutes before the meeting starts
* A live YouTube stream link will be shared a few minutes before the meeting also.

**Comment by maddhruv** [comment]
I am up for the meeting 😊
@obensource the meeting would be on Zoom. Right?

**Comment by bnb** [comment]
@maddhruv yep. I'm grabbing the link now.

**Comment by bnb** [comment]
I'd like to add a small agenda item:

- Defining a consistent time for the i18n meeting to be scheduled.

**Comment by bnb** [comment]
If you will be participating in this meeting as a i18n member, here is the join link: https://zoom.us/j/688543192

If you're interested in watching the meeting as a non-member, here's the YouTube link: youtube.com/nodejs-foundation/live

**Comment by obensource** [comment]
@bnb SWEET! Thanks for hosting us with zoom! Would you be able to get the YT recording going as well?

**Comment by obensource** [comment]
RAD.

**Comment by obensource** [comment]
@bnb that's actually the first item on the agenda: #34 ;)

**Comment by bnb** [comment]
Looks like there's another meeting currently in progress, we may need to start ours a few mins after.

**Comment by obensource** [comment]
Meeting is now available in the original link @bnb shared - https://zoom.us/j/688543192
