### ISSUE TITLE
i18n first meeting

### ISSUE THREAD

**Issue by FranzDeCopenhague** [nodejs/i18n#38]
Hi,

I did join the meeting just started but could not setup the zoom app on time. I would like to join the group and participate in i18n efforts.

**Comment by obensource** [comment]
Thank you @FranzDeCopenhague! Sorry you weren't able to join, but we're excited to have you with us moving forward!

I'll add you as a member ASAP, thanks for jumping in! 🙌

**Comment by obensource** [comment]
Adding! https://github.com/nodejs/i18n/pull/39

Going to close this issue when it merges. Thanks again Franz!
