### ISSUE TITLE
👋 Hi, I wish to Join the Team.

### ISSUE THREAD

**Issue by JoseJPR** [nodejs/i18n#392]
👨🏻‍💻 Hi, I'm Jose, developer for a little over 15 years, I work with JavaScript and the last 6 years with NodeJS.

For months I have been studying for the NodeJS Certification. I have seen that not all content is in Spanish and this may be a barrier for other developers. And ... here I'm, I would like to join the team and be able to help even more. I believe that currently where I can help more is with content translations and I have already started this work.

I'm a very constant person and with a long journey in the OpenSource. I have collaborated with OpenSource al for several years in projects like Apache Cordova and other communities in Spanish like www.phonegapspain.com and www.pwaexperts.io

I update with some more information: 
· Translator: Request to be a Proofreader: https://github.com/nodejs/i18n/issues/293
· Proposal: Feature/git hook i18n translate: https://github.com/nodejs/nodejs.org/pull/3172
· Proposal: Translate the main .md files of this repository into other languages: https://github.com/nodejs/i18n/issues/374

Other content I've created for the community:
· My own preparation for NodeJS Certification: https://github.com/JoseJPR/nodejs-certification
· Tutorial NodeJS REST API Cluster Performance: https://github.com/JoseJPR/tutorial-nodejs-rest-api-cluster-performance
· Tutorial NodeJS Performance Timing: https://github.com/JoseJPR/tutorial-nodejs-performance-timing
· Tutorial NodeJS Net Socket Server and Clients: https://github.com/JoseJPR/tutorial-nodejs-net-socket-server-clients
· Tutorial Fastify with GraphQL and PouchDB: https://github.com/JoseJPR/tutorial-fastify-graphql-pouchdb
· Tutorial Improve the Security of your NodeJS projects with Snyk and Github: https://github.com/JoseJPR/tutorial-security-nodejs-snyk-github
· Tutorial NodeJS Snyk Vuln Cost: https://github.com/JoseJPR/tutorial-nodejs-snyk-vuln-cost

I hope you can add me to the team.

cc/ @nodejs/nodejs-es

**Comment by srl295** [comment]
per @JoseJPR this is a request to join the i18n team

**Comment by obensource** [comment]
@JoseJPR – I'm truly sorry it's taken us this long to add you to the team. You're a constant asset Jose, and we're lucky to work with you. Thanks so much for being a part of this! 🙌

I've created [a PR](https://github.com/nodejs/i18n/pull/495) to add you. Thanks again! 🙏

**Comment by JoseJPR** [comment]
👋 Hi @obensource, don't worry, I know it takes time. I am very happy with the progress. 👏👏👏.
