### ISSUE TITLE
Request to join nodejs i18n team

### ISSUE THREAD

**Issue by amor520** [nodejs/i18n#43]
I come from China  and I'm currently member of the electron/i18n team,request to join nodejs i18n team

**Comment by amor520** [comment]
twitter account  https://twitter.com/amor90s

**Comment by RichardLitt** [comment]
Sounds good to me! Want to open a PR with your name in the list? :)

**Comment by dongfengdejia** [comment]
@RichardLitt , Could i join to the i18n team? i'm from China too.

**Comment by zeke** [comment]
@dongfengdejia you're welcome to join as well. Please add yourself by opening a pull request.

**Comment by laosb** [comment]
@zeke I also want to apply to join, but I didn't have an active Twitter account. Does it matters?

**Comment by RichardLitt** [comment]
@laosb That doesn't matter. You're free to join without one. :)

**Comment by RichardLitt** [comment]
@laosb Open a pull request with your name added and with a little bit about you! :)

**Comment by laosb** [comment]
@RichardLitt , of course will do tonight 😃
