### ISSUE TITLE
Consider third-party i18n services like Transifex or locize

### ISSUE THREAD

**Issue by LaurentGoderre** [nodejs/i18n#44]
I haven't used locize yet but Transifex has some really nice tools for managing i18n. We would split our i18n needs into assets and there's a dashboard to track the percentage of translation for each asset in each supported language.

**Comment by TiagoDanin** [comment]
![image](https://user-images.githubusercontent.com/5731176/37090582-ae3d5af2-21e3-11e8-90c5-8a71609a2f3e.png)
Crowdin has a similar dashboard

**Comment by zeke** [comment]
Thanks for the suggestion @LaurentGoderre, but there is already consensus among the Node.js folks to use Crowdin.

As for Electron, we at GitHub did a rigorous analysis of the available localization platforms, including Transifex, Qordoba, GitLocalize, Acrolinx, LingoHub, and others. Our reasons for choosing Crowdin for the Electron project are enumerated in this document: https://github.com/electron/i18n/blob/master/crowdin.md

**Comment by LaurentGoderre** [comment]
Awesome!!! This might come in handy for projects I'm working on!
