### ISSUE TITLE
Making contact with Crowdin people

### ISSUE THREAD

**Issue by zeke** [nodejs/i18n#5]
It's my understanding that the Node.js project may be using Crowdin as a localization platform. If so, I would recommend @Andrulko as a contact there. Andriy has worked closely with us on the Electron i18n project, and is generally quite responsive to our questions and requests. 🙏

**Comment by Andrulko** [comment]
Hi there!

I will gladly assist with any questions, let's setup something good together :)

**Comment by obensource** [comment]
@zeke wonderful! Thank you for introducing us to @Andrulko! 🙌

@Andrulko At the moment we're in a phase of consensus seeking among our l10n groups concerning our Crowdin/i18n-module proposal. If the results are positive, we will be in touch shortly after to seek out your help! 🎉

Thanks all! 😄

**Comment by Andrulko** [comment]
@obensource Hope 🙏 for positive results of course. Any questions can be shared with me directly. 

Crowdin can solve any localization pain 😎

**Comment by obensource** [comment]
@Andrulko me too. I'm a firm believer in the awesomeness of Crowdin. Hope to be in touch soon! 🙌

**Comment by obensource** [comment]
@Andrulko @zeke right now we're looking good to move forward after today. Excited to be in touch! I'll reach out about getting things rolling with Crowdin tomorrow! 🙌

**Comment by Andrulko** [comment]
I'll be around, excellent!

**Comment by Andrulko** [comment]
Hey @obensource, I've sent you invitation for a quick meeting. Any day, any time, any weather you prefer! :smiley:

**Comment by sotayamashita** [comment]
@Andrulko Could I joint the meeting as a observer?

**Comment by Andrulko** [comment]
@sotayamashita, definitely! Sending you email as well

**Comment by sotayamashita** [comment]
@Andrulko Thanks a lot :smile:

**Comment by Andrulko** [comment]
Of course, if @obensource don't mind :)

**Comment by obensource** [comment]
@Andrulko & @sotayamashita! I've scheduled our meeting time via email and the Calendly invite @Andrulko sent. Let me know if anything comes up (I'm fairly flexible), and if not–I'm excited to see y'all then! 

@zeke let us know if you have interest in joining as well–no problem if not. :)

**Comment by sotayamashita** [comment]
@obensource I cannot find the invitation link. Could you send it again to `sota.yamashita@gmail.com`?

**Comment by Andrulko** [comment]
@sotayamashita please check email / calendar again, you should find an invitation

**Comment by zeke** [comment]
I'd like to join the meeting. Should I have gotten an email?

**Comment by obensource** [comment]
@Andrulko would you mind sending an invite to @zeke? Thanks a bunch, so stoked about this! 🙌

**Comment by obensource** [comment]
@zeke the meeting has been organized by @Andrulko, so he should send you an invite soon if you haven't already received one. 👍

**Comment by Andrulko** [comment]
@obensource, just sent an invitation @zeke. If anyone else wants to join, please drop me a line. You know, I have a feeling that @zeke knows our GitHub integration better than me, so it should be twice efficient! :blush:

**Comment by zeke** [comment]
Got my invitation. See you Monday. 👍

**Comment by obensource** [comment]
Rad! See you then @zeke 🎉

**Comment by zeke** [comment]
@Andrulko can you also invite @vanessayuenn to the call?

**Comment by Andrulko** [comment]
@zeke invitation is sent 📨

**Comment by zeke** [comment]
We had a call!

For the record, these were the attendees:

- @Andrulko from @crowdin
- @sotayamashita from Node.js i18n WG and @gitlocalize
- @obensource from Node.js i18n WG
- @vanessayuenn from @electron and @github 
- @zeke from @electron and @github

Anyone take notes?

**Comment by Andrulko** [comment]
Hope we can get started shortly!

**Comment by obensource** [comment]
@zeke I took a handful of notes. Planning on expanding and sharing them before the upcoming WG meeting. 👍

**Comment by obensource** [comment]
@andrulko we'll be getting our i18n team up to speed and discussing our use of Crowdin at our next WG meeting on the 6th. I imagine the ball will really start to roll soon after that! 🎉🎉🎉

**Comment by obensource** [comment]
Closing this since we've met with @Andrulko, and are now discussion using Crowdin in https://github.com/nodejs/i18n/issues/36.
