### ISSUE TITLE
Request to join nodejs i18n team

### ISSUE THREAD

**Issue by iAndrewCA** [nodejs/i18n#51]
Hi, I am from Poland (currently living in the US) and I would like to join a team nodejs i18n team to help with translations.

**Comment by RichardLitt** [comment]
Welcome, @iAndrewCA! That'd be awesome. Currently, joining is an open process; open a PR with your name and why you'd like to join (or just link to this issue, really).

**Comment by obensource** [comment]
Hi @iAndrewCA! I'm excited to hear more about you and what kind of translation help you'd like to contribute (more specifically). Feel free to answer in [your PR](https://github.com/nodejs/i18n/pull/52). :D 

For example, would you like to help us with Polish translations via Crowdin in a l10n group? Or translate our i18n WG documents into Polish?

Regardless–thank you for wanting to help out, and we're stoked to talk with you! 🙌

**Comment by iAndrewCA** [comment]
Hi @RichardLitt, @obensource 
a little about me: I am a full-stack web developer and I have ~13 experience in programming in different languages (currently working with php/laravel/angular but thinking to switch to node.js).
I currently develop my node.js (or MEAN in general) skills. I really love this platform and I would like to support it and help the node.js community as I can. 
I can work on translating WG documents into Polish

**Comment by obensource** [comment]
@iAndrewCA that sounds great! Thanks so much for sharing a bit more about yourself and what you've been up to!🍻

We're excited to have you with us, and are thankful for your help an any capacity. Thank you for being willing to work on translating our WG docs into Polish, it will help others help us push i18n endeavors forward over time and allow people to keep track of our progress! Super awesome and valuable, appreciate it! 🙌

Thanks for jumping in with us, and feel free to [join us at our next meeting](https://github.com/orgs/nodejs/teams/i18n/discussions/4)!

**Comment by obensource** [comment]
I'll get an issue up that formalizes our WG-documentation translation process, but at the moment I think it would be super awesome if (for example) you could PR a translation of our [first WG meeting doc](https://github.com/nodejs/i18n/blob/master/minutes/2018-03-06.md),  placing it in a new `
i18n/minutes/PL` directory. That'll be an example for others who would like to help us translate our WG docs as well. 

Thanks again @iAndrewCA! Stoked to collaborate with you more! 🍻

**Comment by obensource** [comment]
@iAndrewCA https://github.com/nodejs/i18n/pull/52#pullrequestreview-104644593 has been merged, closing.

Welcome! 🎉
