### ISSUE TITLE
Add new language

### ISSUE THREAD

**Issue by sayuri-gi** [nodejs/i18n#541]
**Projects details**
https://crowdin.com/project/nodejs-website
https://crowdin.com/project/nodejs

**Language details**
Language: Sinhala (සිංහල)
Code: si

Please enable this language for above both projects. I think it's not necessary to open separate issues for this small task and i read all i18n guides then we also intend to propose to create a localization group/team and add a proofreader as well.

I noticed that nodejs team hasn't replied to a language related issue on `nodejs.org` repository for 26 days then i prefer ask, is it ok to contact you through slack [#communication-process](https://github.com/nodejs/i18n/blob/master/guides/GETTING_STARTED.md#communication-process) next time? because it's not comfortable to wait long time.

If you need to mention about the main translator or responsible person for the sinhala language, please use https://github.com/sujithranga details.

**Comment by AugustinMauroy** [comment]
Unfortunately for the nodejs.dev crowdin site is not available. So we go through the translation of the markdown with a text/code editor. If you want to help the project with a translation I advise you to read this [traslation](https://github.com/nodejs/nodejs.dev/blob/1d974c8a38c34615dd43d3b09009708d935e20dd/TRANSLATING.md)
Thanks for your help

Have a good day
AM

**Comment by AugustinMauroy** [comment]
Small news: the migration from nodejs.dev -> to nodejs.org has started so I advise you to follow this to not work in a vacuum.

**Comment by ovflowd** [comment]
> Unfortunately for the nodejs.dev crowdin site is not available. 

That's not accurate, we just lost access to Crowdin. The same applies to Nodejs.org. This has been something on stale for a long period of time, and there's no ETA for when we'll get access to Crowdin back.

**Comment by Trott** [comment]
This repo/group is mostly inactive but there's lots of i18n activity going on at https://crowdin.com/project/nodejs. So if you haven't joined there, consider it!
