### ISSUE TITLE
Request to join the group

### ISSUE THREAD

**Issue by onl1ner** [nodejs/i18n#557]
Hi there! I'd like to become a proofreader for Russian language and join i18n Working Group.

I was very inspired by the opportunity to help with the localization of Node.js and now I have translated more than 3000 words into Russian and brought the translation of three files to 100%. At the moment, I am focused on translating the API documentation and noticed that the percentage of approved translations is very small. I would like to become a proofreader for the Russian language and a member of the group in order to be more deeply involved in the process of internationalization Node.js.

![image](https://user-images.githubusercontent.com/45308586/135107012-f67d51e2-842e-4eb9-b66b-311b96dafab5.png)

**Comment by nschonni** [comment]
Ping @nodejs/nodejs-ru

**Comment by onl1ner** [comment]
@zeke

**Comment by onl1ner** [comment]
Hi there @alexandrtovmach! No, just checked it out and I do not have proofreader role in crowdin. Also could you please review the PR I have opened and I would love to know the answer on that question:

> is there an opportunity to add me to the GitHub team as well?

Thanks!
