### ISSUE TITLE
Automatically apply Translation Memory to new content

### ISSUE THREAD

**Issue by zeke** [nodejs/i18n#56]
We will likely be supporting localization for multiple versions of Node.js documentation. From one version to the next, e.g. `9.9.0` to `9.10.0`, there may be very few changes in the overall content. Rather than relying on translators to re-translate the entirety of Node's documentation from one version to the next, we can use a Crowdin workflow that will automatically apply existing translations from its Translation Memory.

Prior art: https://github.com/electron/i18n/issues/135

**Comment by obensource** [comment]
So stoked about this, super great! 🙌

**Comment by maddhruv** [comment]
But will the whole documentations change for a minor version or just the changelog!

Like the docs should be same for 9.x is think!

So the docs for 9.x.y shall be same :open_mouth:

**Comment by zeke** [comment]
> will the whole documentations change for a minor version

Nope, usually just a small subset of the docs will change. This is indeed an interesting challenge! Having a fully copy of all the docs for every release of Node.js does not seem sustainable.

We could take a step back and ask: On the nodejs.org website, should visitors be able to view docs for ANY version of Node.js?

If **yes**, we'll need to think of a way to manage that volume of docs here. Maybe we can do something clever with diffs...

If **no**, we should agree on an explicit set of versions that we want to support on the website. Could be the latest version of every non-EOL'ed release.

**Comment by maddhruv** [comment]
with the documentations structure can we do like
A super doc for a major release, that is obviously into very minor release also, and then just translating the changelogs only with the flow

Like for instance
The whole 9.1.x shall have the same docs and then we will translate just the changelogs for every minor version 9.x.{y} and concatenate them together!

**Comment by zeke** [comment]
I have configured this using the instructions at https://support.crowdin.com/advanced-workflows/

This can only be administered using the owner account @nodejs-crowdin.

If we ever need to modify this workflow, the URL is https://crowdin.com/resources#workflows

![image](https://user-images.githubusercontent.com/2289/40796754-63d59f0e-6506-11e8-8b63-7333e00ac09f.png)
