### ISSUE TITLE
continuous integration

### ISSUE THREAD

**Issue by zeke** [nodejs/i18n#58]
#55 introduces code into this repository. It would be great if we could run tests on it. I don't know much about CI integration works in the @nodejs org.

**Comment by LaurentGoderre** [comment]
The docker node group uses Travis CI

**Comment by mcollina** [comment]
Hey @zeke, I'm not involved in keeping up the CI. You should talk to @nodejs/build.

**Comment by MylesBorins** [comment]
@zeke we traditionally have allowed integrations on a per case basic. There is prior art for travisCI for example.

Node core uses ci.nodejs.org, a custom Jenkins setup. That system is really only necessary if you are needing to test on specific platforms unsupported by travis.

I think opening an issue on github.com/nodejs/build should be sufficient to get travis enabled here. We need to also open an issue on the TSC repo to talk about updating our bot policy.

**Comment by zeke** [comment]
A PR is in the works: https://github.com/nodejs/github-bot/pull/171

**Comment by zeke** [comment]
Travis is set up! See #94
