### ISSUE TITLE
Crowdin integration with website seems broken

### ISSUE THREAD

**Issue by alexandrtovmach** [nodejs/i18n#582]
Hey guys,

Crowdin integration with nodejs.org repo seems broken, because at [Sep 22, 2021](https://crowdin.com/project/nodejs-website/activity-stream) it just removed all files. I'm out of scope for now, and haven't time to deeply investigate. If someone can check, it'll be great.

Integration should be checked here (I haven't enough rights to fully check it on my side):
https://crowdin.com/project/nodejs-website/apps/system/github

cc: @zeke @obensource

**Comment by JohnTitor** [comment]
Also, the sync process is also broken? It doesn't seem like the translations are actually pushed to the repos by @nodejs-crowdin.

**Comment by AugustinMauroy** [comment]
All integration are broken

**Comment by AugustinMauroy** [comment]
https://github.com/nodejs/nodejs.org/discussions/4994
