### ISSUE TITLE
Require status checks and reviews before PRs can be merged

### ISSUE THREAD

**Issue by zeke** [nodejs/i18n#59]
This is a followup to https://github.com/nodejs/i18n/pull/55

I think we should enforce a review requirement on this repo using [protected branches](https://help.github.com/articles/about-protected-branches/). We could also use GitHub's [CODEOWNERS](https://help.github.com/articles/about-codeowners/) feature to ensure that the right teams and people are able to review pull requests before they ship.

**Comment by RichardLitt** [comment]
Sounds good to me. Who can set this up?

**Comment by zeke** [comment]
I don't have access to the settings tab on this repo.

**Comment by bnb** [comment]
@zeke I've made both you and @RichardLitt a maintainer after discussing briefly with @obensource 👍

**Comment by obensource** [comment]
@bnb wahoo! Thanks. @zeke @RichardLitt let your progress be impeded no more. 🙌

**Comment by zeke** [comment]
Thanks! I still don't seem to have access to repo settings though 🤔

**Comment by RichardLitt** [comment]
Thanks @bnb! Me neither.

**Comment by zeke** [comment]
Good day, @bnb! Can you take another peek at this?

**Comment by bnb** [comment]
@zeke ah my bad - didn't know there was different RBAC for team maintainers and repos, though it totally makes sense. Y'all should have admin rights _for this repo_  (+ @obensource).

**Comment by obensource** [comment]
Thanks for working that out @bnb 👍

**Comment by zeke** [comment]
I've enabled branch protection for `master`. Here's the current configuration:

![image](https://user-images.githubusercontent.com/2289/38508698-c2cb83a8-3bd4-11e8-98d7-a6e02577218b.png)

**Comment by zeke** [comment]
Going to leave this open so we can discuss it during [tomorrow's meeting](#64).

**Comment by zeke** [comment]
Closing this out. We can revisit when and if we need to change our branch protection setup.
