### ISSUE TITLE
new @crowdin-modules org

### ISSUE THREAD

**Issue by zeke** [nodejs/i18n#60]
Now that @nodejs and @electron will both be integrating with Crowdin and facing some of the same challenges, I took a moment to make a new GitHub org for the Crowdin-related modules we're maintaining.

https://github.com/crowdin-modules -- I've invited a few members of @nodejs/i18n to join this org. If you didn't get an invitation and would like to join, please let us know.

- https://github.com/crowdin-modules/get-crowdin-file-ids has been around for a bit.
- https://github.com/crowdin-modules/crowdin-editor-language-codes I just wrote today.

Both of these modules exist to solve two unique parts of the same problem: Given a **language** and a **filename**, how do we get to the Crowdin editor page for that language and document? Crowdin may eventually add new APIs or alternative URLs that will render these modules unnecessary, which would be great! But for now they exist to help us move forward.

cc @andrulko

**Comment by maddhruv** [comment]
add me to the org also @zeke 
I am a member of i18n for node

**Comment by zeke** [comment]
☝️ done

**Comment by lukaszewczak** [comment]
Hi @zeke, could you please add me to this org.

**Comment by zeke** [comment]
☝️ done

**Comment by laosb** [comment]
Could you please have me onboard too :)

**Comment by zeke** [comment]
☝️ done

**Comment by zeke** [comment]
A new module joined the org recently: https://github.com/crowdin-modules/crowdin-glossary

Nothing actionable in this issue, so I'm closing.
