### ISSUE TITLE
I would like to become a member

### ISSUE THREAD

**Issue by lxmarinkovic** [nodejs/i18n#612]
Hi @Trott & @nschonni , I would like to become a member and to contribute with Serbian (Latin or Cyrillic) or translation, mostly for API docs and web site as well

**Comment by Trott** [comment]
@zeke @obensource @RichardLitt Is this still a thing? What should @lxmarinkovic do?

**Comment by RichardLitt** [comment]
I'm unsure. Haven't been active in a while, and I should probably resign from the board as being inactive in general, unfortunately.

**Comment by Trott** [comment]
> I'm unsure. Haven't been active in a while, and I should probably resign from the board as being inactive in general, unfortunately.

I'll remove you as maintainer but leave you as a member unless.

**Comment by zeke** [comment]
Sadly, I have to say the same. I haven't been active in this space for a while and it's a disservice to the community for me to pretend otherwise.

**Comment by RichardLitt** [comment]
> I'll remove you as a maintainer but leave you as a member unless.

This actually sounds good to me. Thanks, @Trott.

**Comment by Trott** [comment]
@obensource @bnb Any chance you can provide guidance here?

**Comment by srl295** [comment]
@obensource

**Comment by ovflowd** [comment]
Hey there 👋 I'm also interested in contributing to the i18n team in general. From this thread it feels like the i18n team is not receiving currently much help, is this correct?

I also saw that the Crowdin integration is broken, and I'd like to help there if possible 👀 (Also with the Website Working Group).

I'd love to chat, @ovflowd:gnome.org on Matrix :)

**Comment by Trott** [comment]
@nodejs/tsc If the larger i18n coordination effort is to be revived, it will need a commitment from leadership, I think. Hopefully someone (@RichardLitt @bnb @obensource @zeke) can confirm or correct this summary but my impression is that:

* The larger i18n effort was a CommComm thing. So it doesn't have a home anymore.
* None of the people who used to lead it are involved in it anymore.
* It's basically broken and in stasis.
* It's different/separate from the general website localization efforts in that....here's where I don't actually know. I *think* the idea was to use Crowdin to make it easier for more people to do translations than our current open-a-pull-request-in-the-nodejs.org-repo method. It may have also had the intention of localization for the API docs but that never came to fruition as far as I know.

I think winding it down and telling people to continue submitting PRs to the website repository is a valid option, and a better option if we're not prepared to put real time and potentially resources (via the foundation, I suppose) into a larger effort. Almost everything that has ever happened with localization happened that way. I'm not sure that this initiative ever bore much fruit (which is fine--lots of things get tried and don't work out). Again, I could be wrong, and maybe one of the folks who was involved in it can comment and add some context or info I don't have.

**Comment by JohnTitor** [comment]
I think your summary comment is almost right. The problem here is that all the folks that have access to Crowdin are out of contact and I cannot promote things to integrate. I feel using Crowdin UI makes translations easier and we should have a lot of translated texts, so integrating into it would be great. Maybe we could focus on API docs for now and continue the current style for the website (submitting PRs to the repo). Or at least I'd like to move the texts on Crowdin to somewhere.

**Comment by Trott** [comment]
> Maybe we could focus on API docs for now

How/where do we published localized API docs? Or is making the translations widely available part of the problem that a larger initiative would solve?

**Comment by TiagoDanin** [comment]
> How/where do we published localized API docs? Or is making the translations widely available part of the problem that a larger initiative would solve?

There is currently an integration (it's broken for the reason @JohnTitor mentioned) between this [repository](https://github.com/nodejs/i18n/tree/main/content) and [Crowdin](https://crowdin.com/project/nodejs/pt-BR). The Crowdin via bot create [PR](https://github.com/nodejs/i18n/pull/674) keep the translated documents synchronized.

Part of the problem we need to solve is making the contents of this repository available to Node.org. 
Part of this discussion can be seen #328 and #315

**Comment by JohnTitor** [comment]
> The Crowdin via bot create [PR](https://github.com/nodejs/i18n/pull/674) keep the translated documents synchronized.

It doesn't update the **translated** docs but the **original** ones. The translated docs are updated like https://github.com/nodejs/i18n/pull/252, I guess it's manually triggered.

**Comment by zeke** [comment]
>  confirm or correct this summary

@Trott alas, your summary is correct from my point of view. I can only speak for myself but, I haven't been able to make time in the last couple years to commit to Node.js i18n effort.

**Comment by ovflowd** [comment]
Note.: My comment stands as I would definitely love to contribute to Internationalisation efforts. I'm also going to contribute to the new node.js website starting with [this](https://github.com/nodejs/nodejs.dev/issues/1555) issue.

I do have open source maintaining experience, and would love to chat on Matrix or any other platform. Sorry for chiming in 😅 🙇

**Comment by mcollina** [comment]
I don't think anybody in the TSC has any availability to restart the i18n and new website projects :(. Managing this kind of initiative is a long-term effort, and we did not do a good job keeping them active.

**Comment by Trott** [comment]
I'll take look at the CrowdIn instance to see if that's at least something we'd like to keep going. We should identify any text anywhere that suggests a larger and more robust initiative and adjust it to the scale of what we're actually doing.

**Comment by ovflowd** [comment]
@mcollina regarding the new website initiative, if we have strong active contributors, is this something we could maybe work on?

I’m on the website redesign slack channel and would love to talk some alternatives and ideas there. Maybe I can be of use here :)

**Comment by mcollina** [comment]
I'm not familiar with the website redesign - minus that it stalled.

**Comment by Trott** [comment]
There certainly seems to be lots of CrowdIn activity and it would be a shame to lose all that work. https://crowdin.com/project/nodejs/activity-stream

Let's see if we can at least fix the integration so this repository can get updated and at least the translated docs will be available.

**Comment by Trott** [comment]
@obensource The CrowdIn interface says you're a manager. Can you log in and make me a manager so I can try to get things going/working again?

**Comment by JohnTitor** [comment]
@obensource It'd be great if you could also add me, my account is https://crowdin.com/profile/huyuumi.

**Comment by JohnTitor** [comment]
Semi-related: how are https://crowdin.com/profile/nodejs-crowdin 's credentials managed? If it's currently shared only within the i18n WG members, it probably should be placed under the control of TSC (or another team? I'm not sure).

**Comment by Trott** [comment]
> Semi-related: how are https://crowdin.com/profile/nodejs-crowdin 's credentials managed? If it's currently shared only within some i18n WG members, it probably should be placed under the control of TSC (or another team? I'm not sure).

I'm guessing it's not exactly the same as the Node.js Crowdin bot's credentials, but just in case: @nodejs/build Is this something Build WG knows anything about?

**Comment by richardlau** [comment]
> > Semi-related: how are https://crowdin.com/profile/nodejs-crowdin 's credentials managed? If it's currently shared only within some i18n WG members, it probably should be placed under the control of TSC (or another team? I'm not sure).
> 
> I'm guessing it's not exactly the same as the Node.js Crowdin bot's credentials, but just in case: @nodejs/build Is this something Build WG knows anything about?

Not to my knowledge.

**Comment by ovflowd** [comment]
For the record, I'm still interested in contributing with i18n, including helping run the team.

I'm primarily curious regarding the `node/i18n` package as we might want to (still) use that for the translations and the docs for https://github.com/nodejs/nodejs.dev website.

cc @Trott 

Off-topic: Oh hey, @JohnTitor fellow GNOME Foundation here 👀

**Comment by Trott** [comment]
Update: I briefly exchanged private messages with `@obensource` and expect to get this moving again soon (as in days, not weeks--famous last words and all that). Nothing more to report at this moment, though.

**Comment by Trott** [comment]
This repo/group is mostly inactive but there's lots of i18n activity going on at https://crowdin.com/project/nodejs. So if you haven't joined there, consider it!
