### ISSUE TITLE
'Getting started' doc for l10n group members

### ISSUE THREAD

**Issue by obensource** [nodejs/i18n#62]
## Purpose
People who're [interested in contributing translations](https://github.com/nodejs/i18n/issues/21) don't have a place to land, or don't know how to get involved yet.

## TODO
A good start will be having a 'Getting Started' doc that contains clear directives for joining l10n groups, which we can link to in our [README](https://github.com/nodejs/i18n/blob/master/README.md) along with a 'Want to help us with translation?' header.

**Comment by alejandronanez** [comment]
If you need this to be translated to Spanish I can help. 👍

**Comment by obensource** [comment]
Rad! Thank you @alejandronanez that would be awesome! 🙌

**Comment by alejandronanez** [comment]
awesome @obensource! Just let me know what's next 🚀

**Comment by obensource** [comment]
@alejandronanez when the related PR lands with this doc definitely feel free to translate it! 🙌

We can use your PR as an opportunity to create a directory for translated WG documents, probably organized by locale. 😄

**Comment by zeke** [comment]
@lukaszewczak that's a good outline. Do you want to start a PR with this list as a starting point, and we can iterate from there?

**Comment by lukaszewczak** [comment]
Hi @zeke, I will prepare PR based on that list.

**Comment by zeke** [comment]
Resolved by #74 and #75 🎉
