### ISSUE TITLE
i18n: test plan

### ISSUE THREAD

**Issue by srl295** [nodejs/i18n#63]
Node.js should be tested against industry tests to verify compatibility for i18n.

Old info:
- https://github.com/caridy/node-intl-testsuite has a way to run the 262 tests against node
   - Background:  https://github.com/nodejs/Intl/issues/15 / https://github.com/nodejs/Intl/issues/13 

Newer:
- https://github.com/bterlson/test262-harness
- https://github.com/tc39/test262/

Maybe the above are already run against node now?

**Comment by maddhruv** [comment]
@srl295 are there any updates here? Can I help in some way?

**Comment by srl295** [comment]
Can you try the test suite above?

**Comment by alexandrtovmach** [comment]
@srl295 Could you write some description to this issue to give us more context, because I have no clue what is going on and how I can help. Thanks

**Comment by srl295** [comment]
> @srl295 Could you write some description to this issue to give us more context, because I have no clue what is going on and how I can help. Thanks

Done.

**Comment by alexandrtovmach** [comment]
@srl295 Can we discuss it on this week meeting?

**Comment by Trott** [comment]
I've unarchived this repo so I can close all PRs and issues before re-archiving.
