### ISSUE TITLE
Next meeting: Tuesday April 10 at 1400 UTC

### ISSUE THREAD

**Issue by RichardLitt** [nodejs/i18n#64]
### What

The next i18n meeting. 

### When

Tuesday April 10th 1400 UTC

See discussion [here](https://github.com/nodejs/i18n/issues/34#issuecomment-378289408). 

### Agenda

* [#19: l10n group audit](https://github.com/nodejs/i18n/issues/19)
* [#34: i18n WG Meeting Time & Frequency](https://github.com/nodejs/i18n/issues/34)
* [#48: Problems found in Electron/i18n from a standpoint of one translator/proofreader](https://github.com/nodejs/i18n/issues/48)
* [#50: Key based i18n vs default language i18n](https://github.com/nodejs/i18n/issues/50)
* [#59: Require status checks and reviews before PRs can be merged](https://github.com/nodejs/i18n/issues/59)
* [#58: continuous integration](https://github.com/nodejs/i18n/issues/58)
* [#60: new @crowdin-modules org](https://github.com/nodejs/i18n/issues/60)
* [#61: File structure and crowdin.yml](https://github.com/nodejs/i18n/issues/61)
* [#62: 'Getting started' doc for l10n group members](https://github.com/nodejs/i18n/issues/62)
* [#63: i18n: test plan](https://github.com/nodejs/i18n/issues/63)

### Where

We'll drop a Zoom link in this room when it is time for the meeting.

**Comment by obensource** [comment]
Thanks you @RichardLitt! 🙌

**Comment by zeke** [comment]
![image](https://user-images.githubusercontent.com/2289/38507004-3b792850-3bd0-11e8-8cbb-fac914df2f09.png)

**Comment by Andrulko** [comment]
Hope to join tomorrow :)

**Comment by bnb** [comment]
Is this time / date consistent? Happy to add a recurring event to the Calendar if they are 😄

**Comment by obensource** [comment]
@bnb not yet, we're trying to nail that down atm. :)

**Comment by obensource** [comment]
@bnb per [this discussion](https://github.com/nodejs/i18n/issues/34#issuecomment-379432191).

**Comment by RichardLitt** [comment]
@zeke - note, that's for tomorrow. Sorry about the 7:00am. Let's figure it out in the meeting, or after. Just trying to get this going, at all.

**Comment by zeke** [comment]
> note, that's for tomorrow. Sorry about the 7:00am

👍

**Comment by Andrulko** [comment]
In 16 minutes 😄

**Comment by bnb** [comment]
Join link: https://zoom.us/j/472283251

**Comment by obensource** [comment]
I've updated our agenda in the meeting description. 🙌

**Comment by TiagoDanin** [comment]
I'll join only to accompany, I speak English I'm very bad 😊

**Comment by lukaszewczak** [comment]
Hey,

I feel a little bad because I was unable to communicate during the call, I use English too little in speech and writing, which lacks the freedom and confidence in using it, but I understand you quite well :-), after all even little active participation (at least for now) gives me a better idea of what is going on in the group and what are the plans.

Second thing, I'm not experienced in the topic of internationalization and crowdin platform and it's hard for me to talk about it, but it would be great if we could made a small demo at one meeting, how exactly the process of translation looks like on the example of Electron which would allow a better understanding of the subject

**Comment by bnb** [comment]
@laosb zero worries! We appreciate you coming and listening in 👍

**Comment by bnb** [comment]
@lukaszewczak We also appreciate you coming and participating in the initiative! Don't worry about not speaking during the meeting - we want to be sure to be inclusive to those who are interested in participating, at the level they're interested in participating at.

I'd also like to say that I'd be interested in a demo of CrowdIn as well - perhaps the full flow of how the Electron team uses it, which is (partially?) what we're basing our usage off of. cc @zeke @obensource

**Comment by lukaszewczak** [comment]
Great! Thank you @zeke

**Comment by Andrulko** [comment]
Just in case, if someone didn't see these videos 😄 
https://www.youtube.com/watch?v=CXomIylZRSY
https://www.youtube.com/watch?v=bxdC7MfrO7A

One is just for fun, another describes all moments in the editor. I also plan to record few videos that describe each tab PMs see in the project settings.

If you have any other ideas what should be described furthermore, please let me know!

**Comment by TiagoDanin** [comment]
> Thank you for joining us @TiagoDanin! Would you like us to provide a translator for you at our next meeting? :raised_hands:

@obensource that would be great :)

**Comment by maddhruv** [comment]
closing :stop_sign:
