### ISSUE TITLE
Spanish and Thai translations

### ISSUE THREAD

**Issue by alphacentauri82** [nodejs/i18n#65]
Hi! i could contribute with Spanish and Thai translations (i guess Thai for documentation since all the coding is done in English).

**Comment by maddhruv** [comment]
Awesome you came up!
Stay tuned with the repo and meeting notes as well

**Comment by maddhruv** [comment]
Check https://github.com/nodejs/nodejs-es repo

**Comment by obensource** [comment]
Closing #62 should resolve this issue.

**Comment by zeke** [comment]
Thanks for your offer to help! We have a new [getting started guide](https://github.com/nodejs/i18n/blob/master/GETTING_STARTED.md) and if all goes well during our [next meeting](#79), we'll have content ready to translate at [crowdin.com/project/nodejs](https://crowdin.com/project/nodejs) by next week. Stay tuned. 🤞
