### ISSUE TITLE
Node.js portuguese internationalization 

### ISSUE THREAD

**Issue by filipecorrea** [nodejs/i18n#67]
I would like to contribute to Node.js portuguese internationalization.

**Comment by maddhruv** [comment]
It's nice having you come up with the contribution!
Stay updated with the repo and as soon as we figure out the right track with internationalization, you can start your magic

**Comment by maddhruv** [comment]
check https://github.com/nodejs/nodejs-pt repo

**Comment by obensource** [comment]
Closing #62 should resolve this issue.

**Comment by zeke** [comment]
Thanks for your offer to help! We have a new [getting started guide](https://github.com/nodejs/i18n/blob/master/GETTING_STARTED.md) and if all goes well during our [next meeting](#79), we'll have content ready to translate at [crowdin.com/project/nodejs](https://crowdin.com/project/nodejs) by next week. Stay tuned. 🤞
