### ISSUE TITLE
I would like to become a member.

### ISSUE THREAD

**Issue by Himself65** [nodejs/i18n#684]
I would like to help and contribute the Chinese translation

**Comment by ischanx** [comment]
+1, how to join and contribute.

**Comment by JohnTitor** [comment]
As stated in https://github.com/nodejs/i18n#joining, translating doesn't require becoming a WG member, you could just start the translation at https://crowdin.com/project/nodejs. What do you want to do in WG?

**Comment by ischanx** [comment]
> As stated in https://github.com/nodejs/i18n#joining, translating doesn't require becoming a WG member, you could just start the translation at https://crowdin.com/project/nodejs. What do you want to do in WG?

thx. i think i get the way to translate! but i want to ask why docs-V18 isn't in crowdin.com

**Comment by JohnTitor** [comment]
> i want to ask why docs-V18 isn't in crowdin.com

That's because our repo doesn't have the original content of v18.x yet. I've added it in #686.

**Comment by Trott** [comment]
This repo/group is mostly inactive but there's lots of i18n activity going on at https://crowdin.com/project/nodejs. So if you haven't joined there, consider it!
