### ISSUE TITLE
No way to read translated docs?

### ISSUE THREAD

**Issue by CodeingBoy** [nodejs/i18n#687]
As I'm getting interested in contributing translations, I'm wondering there's neither "language selection" button on API doc page nor building into [https://nodejs.org/dist/latest-v18.x/docs/](https://nodejs.org/dist/latest-v18.x/docs/). So how we can see these translated version of docs?

**Comment by JohnTitor** [comment]
We haven't deployed the translated docs yet, there's a discussion around it: https://github.com/nodejs/i18n/issues/612#issuecomment-1159472423
TL;DR: folks who have an access to Crowdin are now inactive and we cannot make any progress to deploy the translated docs right now.

To contribute translations, you can still translate the docs on https://crowdin.com/project/nodejs, the materials are stored on Crowdin and we're now trying to use them somehow.

**Comment by CodeingBoy** [comment]
Thanks for reply!
