### ISSUE TITLE
Join to the translation group

### ISSUE THREAD

**Issue by danilsondev** [nodejs/i18n#69]
Hi,
I am interested into join to the translation group for Portugues.

**Comment by maddhruv** [comment]
hey @danilsondev 
awesome :sparkling_heart: 
stay tuned with https://github.com/nodejs/nodejs-pt repo and update with this repo also

**Comment by zeke** [comment]
Thanks for your offer to help! We have a new [getting started guide](https://github.com/nodejs/i18n/blob/master/GETTING_STARTED.md) and if all goes well during our [next meeting](#79), we'll have content ready to translate at [crowdin.com/project/nodejs](https://crowdin.com/project/nodejs) by next week. Stay tuned. 🤞
