### ISSUE TITLE
Request to join node/i18n

### ISSUE THREAD

**Issue by rajzshkr** [nodejs/i18n#7]
Interested in contributing to nodejs, since I'm using it for more than 4 years. I think this will be the right place to start with.

**Comment by sotayamashita** [comment]
@rajzshkr Sorry for replying so late. Could you create a pull request to add? cc:/ @bnb

**Comment by obensource** [comment]
Hi @rajzshkr! Thanks for joining us. I left a comment on you PR. Excited to connect!

**Comment by obensource** [comment]
Hi @rajzshkr! Adding you as a member landed in #11, I'm going to close this. :)
