### ISSUE TITLE
Translation languages

### ISSUE THREAD

**Issue by maddhruv** [nodejs/i18n#70]
Which all languages shall we be targeting initially?
There are ton languages :collision: available with *Crowdin* https://support.crowdin.com/api/language-codes/

Some Commonly translated languages and top languages visited on the website (ref. analytics https://github.com/nodejs/website-redesign/issues/15#issuecomment-369827787)
- Chinese Simplified - [zh-CN](https://github.com/nodejs/nodejs-zh-CN)
- Chinese Traditional - zh-TW
- French - [fr](https://github.com/nodejs/nodejs-fr)
- Russian - [ru](https://github.com/nodejs/nodejs-ru)
- Portuguese - [pt](https://github.com/nodejs/nodejs-pt)
- Spanish - [es](https://github.com/nodejs/nodejs-es)
- German - [de](https://github.com/nodejs/nodejs-de)
- Japanese - [ja](https://github.com/nodejs/nodejs-ja)
- Hindi - [hi](https://github.com/nodejs/nodejs-hi)
- Arabic - [ar](https://github.com/nodejs/nodejs-ar)
- Indonesian - [id](https://github.com/nodejs/nodejs-id)
- Italian - [it](https://github.com/nodejs/nodejs-it)
- Korean - ko
- Polish - [pl](https://github.com/nodejs/nodejs-pl)
- Turkish - [tr](https://github.com/nodejs/nodejs-tr)
- Ukrainian - [uk](https://github.com/nodejs/nodejs-uk)

Amendments highly entertained. :smile:

**Comment by zeke** [comment]
This list lines up very closely with the [most-translated languages for Electron](https://electronjs.org/languages). 👍 

I see just one missing: Filipino 🇵🇭(4th most popular Electron language; currently 89% translated)

Here's some data we used to answer the "which languages?" question for Electron: https://github.com/electron/i18n/issues/4

**Comment by maddhruv** [comment]
actually, I ordered them in the order of languages most visited on the website firstly followed by the electron ones :stuck_out_tongue:

**Comment by laosb** [comment]
Just to point out: zh-TW has its repo at nodejs/nodejs-zh-TW, though they're not maintained in last 3 years. Actually zh-CN group is in a similar state.

**Comment by taggon** [comment]
I dropped a link to [the Korean group](https://github.com/nodejs/nodejs-ko)

**Comment by nodejs-crowdin** [comment]
I am alive!

The following languages have been added:

![image](https://user-images.githubusercontent.com/38230325/40786815-4f51cba8-64ec-11e8-9906-81d9dfa4de96.png)

**Comment by zeke** [comment]
☝️ that was me. Going to close this issue. Feel free to open other language requests in separate issues.
