### ISSUE TITLE
Crowdin integration update

### ISSUE THREAD

**Issue by AugustinMauroy** [nodejs/i18n#714]
# Context

Before there were integrations that allowed to send the original content on the Crowdin platform and then to synchronize them on projects such as nodejs.org. 
But for some time the synchronization does not work anymore.

# Proposal

I propose to recover the admin access to Crowdin to reinstall the synchronization integration.

**Comment by AugustinMauroy** [comment]
cc @nodejs/crowdin-managers-api-docs @nodejs/crowdin-managers

**Comment by JohnTitor** [comment]
The members that have an access to Crowdin are currently inactive and we don't have a way to manage it, see https://github.com/nodejs/i18n/issues/612#issuecomment-1159472423 and the following comments.

**Comment by AugustinMauroy** [comment]
> The members that have an access to Crowdin are currently inactive and we don't have a way to manage it, see [#612 (comment)](https://github.com/nodejs/i18n/issues/612#issuecomment-1159472423) and the following comments.

@Trott have access to crowdin?

**Comment by AugustinMauroy** [comment]
Shouldn't we open an issue about the reorganization of crowdin. In order to use this tool and not to make pull requests on the respective project.

**Comment by Trott** [comment]
> @Trott have access to crowdin?

I have access but haven't made time yet to look into what's involved. @joesepi I assume you haven't either, right?

**Comment by Trott** [comment]
> I have access but haven't made time yet to look into what's involved. @joesepi I assume you haven't either, right?

I've pinged the rest of the TSC to see if we can find a TSC member willing to make this more of a priority than I have managed to.

**Comment by AugustinMauroy** [comment]
If you need someone who has the time to manage all this, I'm willing to do the job.

**Comment by AugustinMauroy** [comment]
If not I can open an exit where I propose to join the WG crowdin. Then I update all this

**Comment by Trott** [comment]
> I propose to join the WG crowdin

No such WG exists.

In my opinion, the TSC needs to be invested in this and not "throw it over the wall" to someone. Working on that. (I'll add it to the next TSC agenda.)

**Comment by Trott** [comment]
We talked about this at the TSC meeting today and I'm going to schedule a meeting with @danielleadams and possibly other TSC folks to figure out how to finally move this forward. Thanks for your patience.

**Comment by AugustinMauroy** [comment]
Hey @Trott do you have any news or din't have time ?

**Comment by alexandrtovmach** [comment]
Hello guys,
Sorry, was unresponsive for last months because of war (still weird to say it). I have access to Crowdin, and I'm able to re-new sync bot in it. Anything new that I should know before start doing that?

Weekly calls works?

**Comment by AugustinMauroy** [comment]
@alexandrtovmach 
Yes, I think you should also check with the website team for the integration of the translated content but yes I think you can already sync the original content on the Crowdin

**Comment by Trott** [comment]
I'm literally talking with @danielleadams about Crowdin right now, so, hey, more people to pull into a meeting or otherwise discuss with. Let's get this thing working! (And I'll probably bow out because clearly I have been ineffective!) (Aside: Thank you, @danielleadams! 🎉 ❤️ 🚀 )

**Comment by alexandrtovmach** [comment]
@Trott could you point me where you had conversations?

**Comment by alexandrtovmach** [comment]
Kindly invite everyone to this meeting, to discuss this and other questions related to i18n:
https://github.com/nodejs/i18n/issues/725

**Comment by Trott** [comment]
> @Trott could you point me where you had conversations?

It was a Zoom meeting with just the two of us, so there's no public record. I explained what (very little) information I had gathered about CrowdIn and i18n stuff, and then we talked about cats.

**Comment by ovflowd** [comment]
Hey @Trott just a friendly ping to check if we've got any updates regarding recovering our Crowdin access? 👀

**Comment by Trott** [comment]
> Hey @Trott just a friendly ping to check if we've got any updates regarding recovering our Crowdin access? 👀

@ovflowd I've made you a manager of the nodejs-website project on Crowdin. There are two other projects (api-docs and nodejs-website-dev) that you may need to join as well, but perhaps not. Hopefully that's enough for you to get some movement going.

**Comment by ovflowd** [comment]
Happy to say our integration with the nodejs.org website is working again after reconfiguring it and updating a few settings and tweaking a few things :)

**Comment by sheplu** [comment]
congrats ! I got the notification yesterday that I can now translate 5000+ items 😆

**Comment by JohnTitor** [comment]
@Trott Could you make me a manager on api-docs and a proofreader of Japanese on nodejs-website?
With that, I should be able to:
- approve translations in Japanese, I'm already a proofreader on api-docs, but not on nodejs-website.
- change the high/low priority settings on api-docs (see the image below), and investigate why integration is broken
![image](https://user-images.githubusercontent.com/25030997/210785515-8c18f6be-9263-4726-8dd4-c4cf401a9724.png)

**Comment by ovflowd** [comment]
Hey, @JohnTitor, I don't think the `api-docs` is used for anything right now. And as we're going in near future to redesign the API docs (https://github.com/nodejs/next-10/issues/166), I'm not sure it makes sense to do anything there for now. IMHO that project could be deleted for now.

I can make you a proofreader on nodejs-website :)

**Comment by JohnTitor** [comment]
@ovflowd Oh great, thanks! Excited to see things are moving forward anyway :)

**Comment by AugustinMauroy** [comment]
For the crowdin look up here: https://github.com/nodejs/nodejs.org/discussions/4994
And for docs translation. look up here: https://github.com/nodejs/next-10/issues/153
