### ISSUE TITLE
i18n WG Meeting

### ISSUE THREAD

**Issue by alexandrtovmach** [nodejs/i18n#725]
### Date & Time
Seems like i18n team regular calls not works anymore, so I can just suggest time, but we can discuss what comfortable for everyone or majority:

6:00pm UTC on December 2nd 2022

### Links
[Google Meet](https://meet.google.com/kcz-pfca-dgv)

### Agenda
* get information from all members about current state of i18n initiative
* talk about TODO plan

> Note: Please feel free to add any issues you'd like to discuss today 👍

### Invited Members
* @nodejs/i18n
* @nodejs/i18n-api 
* @nodejs/nodejs-dev 
* @nodejs/website

### P.S.
I was out of scope for a long time, so missed a lot of updates, and right now it's really hard to understand the full picture of translation process, Crowdin issues, etc., because issues and discussions spread between many node.js repos. It'll be really helpfull to meet each other and summarize all what we have I think.

**Comment by ovflowd** [comment]
Hey 👋 Any Zoom/G Meet link to add?

**Comment by alexandrtovmach** [comment]
Before we used Node.js Zoom instance for calls, but I've never had access to it, so can't manage it on my end. Will ask guys, but if it wouldn't be solved, will add Google Meet link

**Comment by AugustinMauroy** [comment]
I think we should put the link of the issues in the category `Agenda`.

**Comment by AugustinMauroy** [comment]
I propose to add to the to do list:
* Should blog posts be translated?
* Add pending members or close issues and pr

**Comment by alexandrtovmach** [comment]
@AugustinMauroy sounds reasonable, I'll manage creating roadmap after meeting. The rest of questions need to check in team discussion. And yeah, I'd be happy to add all issues, but I'm out of context which one I should add now, and which is already deprecated

**Comment by AugustinMauroy** [comment]
@alexandrtovmach it's a list of things to do in the long term

**Comment by AugustinMauroy** [comment]
I can't join the meet

**Comment by AugustinMauroy** [comment]
<img width="1074" alt="Capture d’écran 2022-12-02 à 19 10 43" src="https://user-images.githubusercontent.com/97875033/205358266-e5aec4fe-ee78-44ac-b0da-249b9d7e2d09.png">

**Comment by ovflowd** [comment]
I think the call should be postponed, you should give more time for people to have their availability set 😅

I honestly recommend making a poll for people to join.

**Comment by alexandrtovmach** [comment]
yeah, I know how it can be))

**Comment by JohnTitor** [comment]
> Seems like i18n team regular calls not works anymore

We've disabled the workflow as WG was inactive, you could re-enable it at https://github.com/nodejs/i18n/actions/workflows/create-meeting-issue.yml.

**Comment by AugustinMauroy** [comment]
Finish!

**Comment by ovflowd** [comment]
@AugustinMauroy, why you closed this issue? A new meeting wasn't scheduled yet 🤔 

@alexandrtovmach please let us know whether you have updates or not 🙂

**Comment by AugustinMauroy** [comment]
@ovflowd the meeting was done an other issue was open for disscuting about long therme of I18n teams.

**Comment by ovflowd** [comment]
I don't see the issue being referenced here, neither @alexandrtovmach mentioning if they were able to reactivate the Workflow.
