### ISSUE TITLE
WG meeting: long terme of teams

### ISSUE THREAD

**Issue by AugustinMauroy** [nodejs/i18n#735]
# Goal of issue

For the "restart" of the I18n team, several questions arise. 

The first one being when are you available for a meeting.
The second one is how do you see the team. And how can we reinvigorate it.

The purpose of this re-launch is to coordinate the I18n team in the translation of the website redesing content and other projects

## What can you do

Given your time availability for the WG.

Give your opinion on the outcome itself. And give your opinion on the agenda.

## Date & Time

* undefined 

## Links

* [Zoom] link will give by member have access to zoom

## The topics of his next W.G. meeting

* Discute about what will we do with `website-dev` Crowdin project 
* Review all open issues and PR.
* Add members that need to be added
* Planning the translation of projects
* See if there are any inactive members that should be removed from the team 

> All this is a proposal it is of course subject to discussion. Whether on this issue or on Slack.

## Finally

It will be necessary to draw up the roadmap / guideline for 2023++

Thank you to all contributors for your help in making the contents of the foundation in any language. And thank you for taking the time to read and respond to this issue.

**Comment by AugustinMauroy** [comment]
@nodejs/i18n

**Comment by zeusdeux** [comment]
I am available starting Jan 9th (GMT+5:30). If we kick it off in Feb instead, then GMT+1 (which would be preferred).
Regarding reinvigorating it, a set direction would help. For e.g., by 2023 we want full doc coverage in language X, Y and Z.
That way we can rally folks under a common flag. Just my 2 cents.

**Comment by AugustinMauroy** [comment]
@zeusdeux I totally agree with you that the main objective of the first meeting is to define the path to take.

**Comment by zeusdeux** [comment]
I'd be down! It would be nice to setup multiple sessions with the same core (for e.g., yourself and I am happy to join as well) so that folks have a wider pool to optimize for attendance.
