### ISSUE TITLE
Next meeting: Tuesday May 15th at 8am Pacific

### ISSUE THREAD

**Issue by RichardLitt** [nodejs/i18n#79]
It's time for another meeting folks! I know that the last meeting was at a poor time for the California folks, so let's set it in favor of them this time, following https://github.com/nodejs/i18n/issues/34#issuecomment-373512470. Does this time work for everyone?

- **PST: 8 AM - 9 AM**
- EST: 11am-12pm
- CET: 6am-7am
- CST: 1pm-2pm
- JST:  12pm-1pm

### Agenda
- continuous integration #58 
- Translation languages #70 
- Versions to Translate #71 
- website content to be translated #72 
- Set up the Crowdin-GitHub integration together, and record it #77 
New project board #82 

*Edit: Added agenda and also changed time*

**Comment by zeke** [comment]
10pm is a generally a bit little late for me (embarrassing I know, but I have young kids now and they wake up very early 🐒🌞🐒) BUT I could make this time if it works for everyone else.

**Comment by maddhruv** [comment]
The same for me is 9:30 in the morning.
Works fine at this time. No Kids, No GF :stuck_out_tongue: single boy wakes up at 4AM :laughing:

**Comment by RichardLitt** [comment]
@zeke Fair! In that case; what is a good time for you?

**Comment by zeke** [comment]
> We can also move this date to the 15th.

👍 I'd be in favor of this. That way @RichardLitt can attend, more people can clear their schedule for it ahead of time, and I'll have more runway to prepare for the call (I have yet to attempt the @nodejs [shared credentials GPG dance](https://github.com/nodejs/build/issues/1220))

**Comment by lukaszewczak** [comment]
Pretty much any time of day works for me, and we can move this to the 15th.

**Comment by RichardLitt** [comment]
Let's move it to the 15th. Done. 

Regarding time: how about we move it to the morning, then? 

    PST: 7am-8am
    CET: 10pm-11pm
    CST: 3pm-4pm

**Comment by zeke** [comment]
That works for me 👍

**Comment by lukaszewczak** [comment]
Probably it would be ok for me too, but it looks that it will be 5 pm in CET, 

![image](https://user-images.githubusercontent.com/7238770/39746874-f780f388-52ab-11e8-9555-233245112131.png)

**Comment by zeke** [comment]
Hey @nodejs/i18n! Looking forward to our meeting tomorrow. Who's planning to attend?

Things to figure out:

- [ ] meeting URL (@bnb halp!?)
- [ ] recording the call
- [ ] notetaker

We can use this project too: https://github.com/nodejs/i18n/projects/1

**Comment by obensource** [comment]
@zeke I'm there. See y'all at 8am PST! Wahoo! 🙌

Pretty sure we can just use the Foundation's zoom channel since nothing is scheduled for Node at that time. @bnb can @zeke and I get auth to use the Foundation's zoom account for our i18n WG meetings? It'd be awesome if you could give us the low-down on utilizing the YT stream, etc (is streaming/publishing configured to run with the zoom record feature?). Super thankful you've been able to facilitate that for our WG so far btw! 👍

**Comment by obensource** [comment]
If all else fails–we can just hold our zoom meeting [here](https://invisionapp.zoom.us/j/418616800), record it, and manually publish after. :)

**Comment by maddhruv** [comment]
8 AM PT done :+1:

**Comment by vanessayuenn** [comment]
@obensource where do I find the link to the Foundation's zoom?

**Comment by Andrulko** [comment]
I'm sorry to say that I have 2 meetings in a row (8am PST and 9am PST)... Hope my colleagues can join the discussion

**Comment by obensource** [comment]
@vanessayuenn foundation meetings are always held [here](https://zoom.us/j/209550902), and the [calendar](https://calendar.google.com/calendar/embed?src=nodejs.org_nr77ama8p7d7f9ajrpnu506c98%40group.calendar.google.com) is the best indicator for when it's being used.

Our meeting is on the calendar, but I'm not sure if @bnb is going to be able to join us yet and facilitate the recording+live-stream (I haven't done it before). I think we should plan to meet [here](https://invisionapp.zoom.us/j/418616800) today so we can capture it, unless @bnb is available. :)

**Comment by obensource** [comment]
@vanessayuenn @maddhruv @zeke @Tiriel @RichardLitt @lukaszewczak just confirmed with @bnb we can meet on the official node zoom, see you there! 🎉🎉🎉

https://zoom.us/j/209550902

**Comment by srl295** [comment]
I'll probably miss this, my regrets

**Comment by obensource** [comment]
The address was wrong, updated^

**Comment by obensource** [comment]
@srl295 no worries, excited to see you next time! :D

**Comment by rohalskyy** [comment]
Will gladly join the discussion

**Comment by rachelnicole** [comment]
I'm sick but I'm excited to catch up at the collab summit

**Comment by obensource** [comment]
Thanks for your patience, just got the link from the @bnb–here we go!

https://zoom.us/j/196918186

**Comment by obensource** [comment]
*disregard the previous links I shared.

**Comment by sotayamashita** [comment]
@obensource Can I join ?

**Comment by lukaszewczak** [comment]
Unfortunately, I had technical dificulties today, :-( and I do not want to interupt in the middle of the meeting, I will watch it on yt.

**Comment by zeke** [comment]
This meeting happened! Here are the notes: https://gist.github.com/zeke/6ab3b52bb1a1e1f45e7707cfc5a5753e

We also recorded the call. @obensource will follow up with a link to the video.

**Comment by zeke** [comment]
Video is up: https://www.youtube.com/watch?v=lfIra3g39uA
