### ISSUE TITLE
Count me in

### ISSUE THREAD

**Issue by Volem** [nodejs/i18n#8]
I would like to join the group and contribute to i18n initiative

**Comment by obensource** [comment]
@Volem my apologies for the delay as well. Thank you for joining us! Please submit a PR adding your name to our README, and we'll add you to the group! Excited to connect soon! :D

**Comment by Volem** [comment]
Please find the PR #29

**Comment by RichardLitt** [comment]
Thanks @Volem! Looking forward to interfacing!
