### ISSUE TITLE
Create Crowdin Glossary

### ISSUE THREAD

**Issue by zeke** [nodejs/i18n#81]
Crowdin has a glossary feature that presents translators with useful information about the terms they're translating (or should not be translating). Here's an example:

<img width="603" alt="36569408-8a4ad454-17e2-11e8-8a5b-9c394db0eafd" src="https://user-images.githubusercontent.com/2289/39786223-6dbc570e-52d4-11e8-9d0e-e36ac20ef3cb.png">

For nodejs/i18n, we should probably start with the following:

- node module names: `fs`, `path`, `net`, etc
- JavaScript builtins like `Array`, `Boolean`, etc. We can use the [builtins](https://ghub.io/builtins) module for this.

I've extracted our Crowdin glossary code from electron/i18n and created a new node module [crowdin-glossary](https://ghub.io/crowdin-glossary) that we can use:

```js
const glossary = require('crowdin-glossary')({
  project: 'nodejs'
})

Object.keys(globals.builtin).forEach(term => {
  glossary.add(term, 'This is a JavaScript builtin and should usually not be translated.')
})
 
glossary.upload()
```

For more info on Electron's glossaries, see https://github.com/electron/i18n/blob/master/contributing.md#glossaries

**Comment by lukaszewczak** [comment]
Hi @zeke , I can prepare PR with such a script for nodejs/i18n
