### ISSUE TITLE
Create Slack Workspace for communication between translators.

### ISSUE THREAD

**Issue by ryo-a** [nodejs/i18n#85]
(I pointed out the lack of communication between translators in #48. This is a follow-up issue for a project board.)
I have an idea that we launch the Slack Workspace for translators/proofreaders and link it from [Crowdin](https://crowdin.com/project/nodejs). It is better to make the workspace public with [slack-invite-automation](https://github.com/outsideris/slack-invite-automation) and so on.

(If there is any problem to add this issue to the project board, please tell me :bow:)

**Comment by maddhruv** [comment]
We already have an *i18n* channel in the Node.js Slack, better is to put a reference to the same here in the repository in `Getting-started/Contributing` section?

**Comment by ryo-a** [comment]
I think translators need the place for communication in their own language.
so it is good for creating channels for each languages (like #es,#fr,#ja,#zh-TW...).

However, creating many channels (for each languages) just for i18n/l10n on Node.js Slack isn't good way...
This is why I suggest to create new workspace.

**Comment by lukaszewczak** [comment]
Hi, as I proposed in [Getting Started doc](https://github.com/nodejs/i18n/blob/master/GETTING_STARTED.md#the-role-of-the-l10n-group), the place for translators for communication will be in l10n groups at the moment. 

In any case, I do not insist on this, but thanks to that existing groups could be used, opening the topic does not require specific knowledge of how GitHub works, in case the translator is not a technical person.

If we think about using Slack, I'm on using current Node.js Slack, which is used by the community and it is a good place to find help. If there are no objections from Node.js Slack admins to create about 35 channels for each language, I do not see a need to introduce new workspace for the community,

**Comment by zeke** [comment]
> Node.js Slack

How do I join this?

> create about 35 channels for each language

We could start with a single #i18n channel and see how it goes. 🤔

**Comment by lukaszewczak** [comment]
@zeke please go to this page http://www.nodeslackers.com/ and register, you should receive an email with access details.

There is already #i18n channel, so we can meet there.

**Comment by zeke** [comment]
> http://www.nodeslackers.com/

Should we add this to the getting started guide?

**Comment by amorist** [comment]
#90 So, now close this issue
