### ISSUE TITLE
Request to join i18n WG

### ISSUE THREAD

**Issue by JCMais** [nodejs/i18n#9]
I'm currently member of the `nodejs-pt` i10n group, and I would like to be part of this WG.

**Comment by sotayamashita** [comment]
@JCMais Sorry for replying so late. Could you create a pull request to add? cc:/ @bnb

**Comment by JCMais** [comment]
@sotayamashita done https://github.com/nodejs/i18n/pull/11

**Comment by obensource** [comment]
Thank you @JCMais, I've approved your PR. Excited to have you with us!

**Comment by obensource** [comment]
@JCMais merged #11. Thanks for alphabetizing us! :D
