### ISSUE TITLE
npm account for publishing nodejs-i18n module

### ISSUE THREAD

**Issue by zeke** [nodejs/i18n#93]
As part of #92, we'll need a shared npm user (or npm organization) for publishing the module.

@bnb @rvagg is there any precedent for this?

**Comment by bnb** [comment]
cc @mhdawson @MylesBorins would be great to get your input if y'all have context 🤔

**Comment by bnb** [comment]
Ah, it looks like there's a Node.js Foundation account: https://www.npmjs.com/~nodejs-foundation

**Comment by maddhruv** [comment]
Looks like the package - https://www.npmjs.com/package/nodejs-i18n is already taken by one of our contributors - https://github.com/TiagoDanin @TiagoDanin 
if he is convinced to transfer the ownership, we can add `nodejs-foundation` npm user as the owner and others as collaborators.

Until the i18n module is in WIP, let's figure out the package name and credentials first. What say @zeke @obensource

**Comment by zeke** [comment]
It looks like the `nodejs-i18n` project is still actively maintained, with a commit from 9 days ago. @TiagoDanin is indeed a friend of the Node.js i18n effort here, so maybe that project could be renamed to make way for this module.

As an alternative, what about using the `@nodejs` scope and publishing the package at `@nodejs/i18n`? It looks like there's no precedent for that, as I don't see any packages here: https://www.npmjs.com/org/nodejs -- But maybe we could blaze that trail...

cc @bnb,@Trott, and @rvagg who might have some context on who owns that npm org.

**Comment by zeke** [comment]
Sorry, should have read the whole thread before commenting!

`@nodejs-foundation/i18n` sounds good to me 👍

**Comment by mhdawson** [comment]
I guess I missed this way back then.

The approach we've taken for other modules under the Node.js project is to publish them from individual accounts (ie adding people as maintainers in npm) and also adding the nodejs-foundation as a maintainer. nodejs-foundation account would only be used to add new maintainers in the case were the other maintainers are no longer active. Publishes would still done from the invidual accounts. As an example you can look at: https://www.npmjs.com/package/node-addon-api as an example.

**Comment by alexandrtovmach** [comment]
Closing in favor #261
